<?php
/**
 * THEME WAR WordPress Framework
 *
 * Copyright (c) 2016, THEME WAR,(http://themewar.com)
 */

function martin_filter_theme_new_icon_set($sets) {
    $elIcons = '.arrow_up, .arrow_down, .arrow_left, .arrow_right, .arrow_left-up, .arrow_right-up, .arrow_right-down, .arrow_left-down, .arrow-up-down, .arrow_up-down_alt, .arrow_left-right_alt, .arrow_left-right, .arrow_expand_alt2, .arrow_expand_alt, .arrow_condense, .arrow_expand, .arrow_move, .arrow_carrot-up, .arrow_carrot-down, .arrow_carrot-left, .arrow_carrot-right, .arrow_carrot-2up, .arrow_carrot-2down, .arrow_carrot-2left, .arrow_carrot-2right, .arrow_carrot-up_alt2, .arrow_carrot-down_alt2, .arrow_carrot-left_alt2, .arrow_carrot-right_alt2, .arrow_carrot-2up_alt2, .arrow_carrot-2down_alt2, .arrow_carrot-2left_alt2, .arrow_carrot-2right_alt2, .arrow_triangle-up, .arrow_triangle-down, .arrow_triangle-left, .arrow_triangle-right, .arrow_triangle-up_alt2, .arrow_triangle-down_alt2, .arrow_triangle-left_alt2, .arrow_triangle-right_alt2, .arrow_back, .icon_minus-06, .icon_plus, .icon_close, .icon_check, .icon_minus_alt2, .icon_plus_alt2, .icon_close_alt2, .icon_check_alt2, .icon_zoom-out_alt, .icon_zoom-in_alt, .icon_search, .icon_box-empty, .icon_box-selected, .icon_minus-box, .icon_plus-box, .icon_box-checked, .icon_circle-empty, .icon_circle-slelected, .icon_stop_alt2, .icon_stop, .icon_pause_alt2, .icon_pause, .icon_menu, .icon_menu-square_alt2, .icon_menu-circle_alt2, .icon_ul, .icon_ol, .icon_adjust-horiz, .icon_adjust-vert, .icon_document_alt, .icon_documents_alt, .icon_pencil, .icon_pencil-edit_alt, .icon_pencil-edit, .icon_folder-alt, .icon_folder-open_alt, .icon_folder-add_alt, .icon_info_alt, .icon_error-oct_alt, .icon_error-circle_alt, .icon_error-triangle_alt, .icon_question_alt2, .icon_question, .icon_comment_alt, .icon_chat_alt, .icon_vol-mute_alt, .icon_volume-low_alt, .icon_volume-high_alt, .icon_quotations, .icon_quotations_alt2, .icon_clock_alt, .icon_lock_alt, .icon_lock-open_alt, .icon_key_alt, .icon_cloud_alt, .icon_cloud-upload_alt, .icon_cloud-download_alt, .icon_image, .icon_images, .icon_lightbulb_alt, .icon_gift_alt, .icon_house_alt, .icon_genius, .icon_mobile, .icon_tablet, .icon_laptop, .icon_desktop, .icon_camera_alt, .icon_mail_alt, .icon_cone_alt, .icon_ribbon_alt, .icon_bag_alt, .icon_creditcard, .icon_cart_alt, .icon_paperclip, .icon_tag_alt, .icon_tags_alt, .icon_trash_alt, .icon_cursor_alt, .icon_mic_alt, .icon_compass_alt, .icon_pin_alt, .icon_pushpin_alt, .icon_map_alt, .icon_drawer_alt, .icon_toolbox_alt, .icon_book_alt, .icon_calendar, .icon_film, .icon_table, .icon_contacts_alt, .icon_headphones, .icon_lifesaver, .icon_piechart, .icon_refresh, .icon_link_alt, .icon_link, .icon_loading, .icon_blocked, .icon_archive_alt, .icon_heart_alt, .icon_star_alt, .icon_star-half_alt, .icon_star, .icon_star-half, .icon_tools, .icon_tool, .icon_cog, .icon_cogs, .arrow_up_alt, .arrow_down_alt, .arrow_left_alt, .arrow_right_alt, .arrow_left-up_alt, .arrow_right-up_alt, .arrow_right-down_alt, .arrow_left-down_alt, .arrow_condense_alt, .arrow_expand_alt3, .arrow_carrot_up_alt, .arrow_carrot-down_alt, .arrow_carrot-left_alt, .arrow_carrot-right_alt, .arrow_carrot-2up_alt, .arrow_carrot-2dwnn_alt, .arrow_carrot-2left_alt, .arrow_carrot-2right_alt, .arrow_triangle-up_alt, .arrow_triangle-down_alt, .arrow_triangle-left_alt, .arrow_triangle-right_alt, .icon_minus_alt, .icon_plus_alt, .icon_close_alt, .icon_check_alt, .icon_zoom-out, .icon_zoom-in, .icon_stop_alt, .icon_menu-square_alt, .icon_menu-circle_alt, .icon_document, .icon_documents, .icon_pencil_alt, .icon_folder, .icon_folder-open, .icon_folder-add, .icon_folder_upload, .icon_folder_download, .icon_info, .icon_error-circle, .icon_error-oct, .icon_error-triangle, .icon_question_alt, .icon_comment, .icon_chat, .icon_vol-mute, .icon_volume-low, .icon_volume-high, .icon_quotations_alt, .icon_clock, .icon_lock, .icon_lock-open, .icon_key, .icon_cloud, .icon_cloud-upload, .icon_cloud-download, .icon_lightbulb, .icon_gift, .icon_house, .icon_camera, .icon_mail, .icon_cone, .icon_ribbon, .icon_bag, .icon_cart, .icon_tag, .icon_tags, .icon_trash, .icon_cursor, .icon_mic, .icon_compass, .icon_pin, .icon_pushpin, .icon_map, .icon_drawer, .icon_toolbox, .icon_book, .icon_contacts, .icon_archive, .icon_heart, .icon_profile, .icon_group, .icon_grid-2x2, .icon_grid-3x3, .icon_music, .icon_pause_alt, .icon_phone, .icon_upload, .icon_download, .social_facebook, .social_twitter, .social_pinterest, .social_googleplus, .social_tumblr, .social_tumbleupon, .social_wordpress, .social_instagram, .social_dribbble, .social_vimeo, .social_linkedin, .social_rss, .social_deviantart, .social_share, .social_myspace, .social_skype, .social_youtube, .social_picassa, .social_googledrive, .social_flickr, .social_blogger, .social_spotify, .social_delicious, .social_facebook_circle, .social_twitter_circle, .social_pinterest_circle, .social_googleplus_circle, .social_tumblr_circle, .social_stumbleupon_circle, .social_wordpress_circle, .social_instagram_circle, .social_dribbble_circle, .social_vimeo_circle, .social_linkedin_circle, .social_rss_circle, .social_deviantart_circle, .social_share_circle, .social_myspace_circle, .social_skype_circle, .social_youtube_circle, .social_picassa_circle, .social_googledrive_alt2, .social_flickr_circle, .social_blogger_circle, .social_spotify_circle, .social_delicious_circle, .social_facebook_square, .social_twitter_square, .social_pinterest_square, .social_googleplus_square, .social_tumblr_square, .social_stumbleupon_square, .social_wordpress_square, .social_instagram_square, .social_dribbble_square, .social_vimeo_square, .social_linkedin_square, .social_rss_square, .social_deviantart_square, .social_share_square, .social_myspace_square, .social_skype_square, .social_youtube_square, .social_picassa_square, .social_googledrive_square, .social_flickr_square, .social_blogger_square, .social_spotify_square, .social_delicious_square, .icon_printer, .icon_calulator, .icon_building, .icon_floppy, .icon_drive, .icon_search-2, .icon_id, .icon_id-2, .icon_puzzle, .icon_like, .icon_dislike, .icon_mug, .icon_currency, .icon_wallet, .icon_pens, .icon_easel, .icon_flowchart, .icon_datareport, .icon_briefcase, .icon_shield, .icon_percent, .icon_globe, .icon_globe-2, .icon_target, .icon_hourglass, .icon_balance, .icon_rook, .icon_printer-alt, .icon_calculator_alt, .icon_building_alt, .icon_floppy_alt, .icon_drive_alt, .icon_search_alt, .icon_id_alt, .icon_id-2_alt, .icon_puzzle_alt, .icon_like_alt, .icon_dislike_alt, .icon_mug_alt, .icon_currency_alt, .icon_wallet_alt, .icon_pens_alt, .icon_easel_alt, .icon_flowchart_alt, .icon_datareport_alt, .icon_briefcase_alt, .icon_shield_alt, .icon_percent_alt, .icon_globe_alt, .icon_clipboard';
    $elIconsa = explode(',', $elIcons);
    
    $simpleIcon = '.icon-user-female, .icon-user-follow, .icon-user-following, .icon-user-unfollow, .icon-trophy, .icon-screen-smartphone, .icon-screen-desktop, .icon-plane, .icon-notebook, .icon-moustache, .icon-mouse, .icon-magnet, .icon-energy, .icon-emoticon-smile, .icon-disc, .icon-cursor-move, .icon-crop, .icon-credit-card, .icon-chemistry, .icon-user, .icon-speedometer, .icon-social-youtube, .icon-social-twitter, .icon-social-tumblr, .icon-social-facebook, .icon-social-dropbox, .icon-social-dribbble, .icon-shield, .icon-screen-tablet, .icon-magic-wand, .icon-hourglass, .icon-graduation, .icon-ghost, .icon-game-controller, .icon-fire, .icon-eyeglasses, .icon-envelope-open, .icon-envelope-letter, .icon-bell, .icon-badge, .icon-anchor, .icon-wallet, .icon-vector, .icon-speech, .icon-puzzle, .icon-printer, .icon-present, .icon-playlist, .icon-pin, .icon-picture, .icon-map, .icon-layers, .icon-handbag, .icon-globe-alt, .icon-globe, .icon-frame, .icon-folder-alt, .icon-film, .icon-feed, .icon-earphones-alt, .icon-earphones, .icon-drop, .icon-drawer, .icon-docs, .icon-directions, .icon-direction, .icon-diamond, .icon-cup, .icon-compass, .icon-call-out, .icon-call-in, .icon-call-end, .icon-calculator, .icon-bubbles, .icon-briefcase, .icon-book-open, .icon-basket-loaded, .icon-basket, .icon-bag, .icon-action-undo, .icon-action-redo, .icon-wrench, .icon-umbrella, .icon-trash, .icon-tag, .icon-support, .icon-size-fullscreen, .icon-size-actual, .icon-shuffle, .icon-share-alt, .icon-share, .icon-rocket, .icon-question, .icon-pie-chart, .icon-pencil, .icon-note, .icon-music-tone-alt, .icon-music-tone, .icon-microphone, .icon-loop, .icon-logout, .icon-login, .icon-list, .icon-like, .icon-home, .icon-grid, .icon-graph, .icon-equalizer, .icon-dislike, .icon-cursor, .icon-control-start, .icon-control-rewind, .icon-control-play, .icon-control-pause, .icon-control-forward, .icon-control-end, .icon-calendar, .icon-bulb, .icon-bar-chart, .icon-arrow-up, .icon-arrow-right, .icon-arrow-left, .icon-arrow-down, .icon-ban, .icon-bubble, .icon-camcorder, .icon-camera, .icon-check, .icon-clock, .icon-close, .icon-cloud-download, .icon-cloud-upload, .icon-doc, .icon-envelope, .icon-eye, .icon-flag, .icon-folder, .icon-heart, .icon-info, .icon-key, .icon-link, .icon-lock, .icon-lock-open, .icon-magnifier, .icon-magnifier-add, .icon-magnifier-remove, .icon-paper-clip, .icon-paper-plane, .icon-plus, .icon-pointer, .icon-power, .icon-refresh, .icon-reload, .icon-settings, .icon-star, .icon-symbol-female, .icon-symbol-male, .icon-target, .icon-volume-1, .icon-volume-2, .icon-volume-off, .icon-users';
    $simpleIcona = explode(',', $simpleIcon);
    
    $font_awesome_icons = array( 'fa-glass' => '\f000', 'fa-music' => '\f001', 'fa-search' => '\f002', 'fa-envelope-o' => '\f003', 'fa-heart' => '\f004', 'fa-star' => '\f005', 'fa-star-o' => '\f006', 'fa-user' => '\f007', 'fa-film' => '\f008', 'fa-th-large' => '\f009', 'fa-th' => '\f00a', 'fa-th-list' => '\f00b', 'fa-check' => '\f00c', 'fa-times' => '\f00d', 'fa-search-plus' => '\f00e', 'fa-search-minus' => '\f010', 'fa-power-off' => '\f011', 'fa-signal' => '\f012', 'fa-cog' => '\f013', 'fa-trash-o' => '\f014', 'fa-home' => '\f015', 'fa-file-o' => '\f016', 'fa-clock-o' => '\f017', 'fa-road' => '\f018', 'fa-download' => '\f019', 'fa-arrow-circle-o-down' => '\f01a', 'fa-arrow-circle-o-up' => '\f01b', 'fa-inbox' => '\f01c', 'fa-play-circle-o' => '\f01d', 'fa-repeat' => '\f01e', 'fa-refresh' => '\f021', 'fa-list-alt' => '\f022', 'fa-lock' => '\f023', 'fa-flag' => '\f024', 'fa-headphones' => '\f025', 'fa-volume-off' => '\f026', 'fa-volume-down' => '\f027', 'fa-volume-up' => '\f028', 'fa-qrcode' => '\f029', 'fa-barcode' => '\f02a', 'fa-tag' => '\f02b', 'fa-tags' => '\f02c', 'fa-book' => '\f02d', 'fa-bookmark' => '\f02e', 'fa-print' => '\f02f', 'fa-camera' => '\f030', 'fa-font' => '\f031', 'fa-bold' => '\f032', 'fa-italic' => '\f033', 'fa-text-height' => '\f034', 'fa-text-width' => '\f035', 'fa-align-left' => '\f036', 'fa-align-center' => '\f037', 'fa-align-right' => '\f038', 'fa-align-justify' => '\f039', 'fa-list' => '\f03a', 'fa-outdent' => '\f03b', 'fa-indent' => '\f03c', 'fa-video-camera' => '\f03d', 'fa-picture-o' => '\f03e', 'fa-pencil' => '\f040', 'fa-map-marker' => '\f041', 'fa-adjust' => '\f042', 'fa-tint' => '\f043', 'fa-pencil-square-o' => '\f044', 'fa-share-square-o' => '\f045', 'fa-check-square-o' => '\f046', 'fa-arrows' => '\f047', 'fa-step-backward' => '\f048', 'fa-fast-backward' => '\f049', 'fa-backward' => '\f04a', 'fa-play' => '\f04b', 'fa-pause' => '\f04c', 'fa-stop' => '\f04d', 'fa-forward' => '\f04e', 'fa-fast-forward' => '\f050', 'fa-step-forward' => '\f051', 'fa-eject' => '\f052', 'fa-chevron-left' => '\f053', 'fa-chevron-right' => '\f054', 'fa-plus-circle' => '\f055', 'fa-minus-circle' => '\f056', 'fa-times-circle' => '\f057', 'fa-check-circle' => '\f058', 'fa-question-circle' => '\f059', 'fa-info-circle' => '\f05a', 'fa-crosshairs' => '\f05b', 'fa-times-circle-o' => '\f05c', 'fa-check-circle-o' => '\f05d', 'fa-ban' => '\f05e', 'fa-arrow-left' => '\f060', 'fa-arrow-right' => '\f061', 'fa-arrow-up' => '\f062', 'fa-arrow-down' => '\f063', 'fa-share' => '\f064', 'fa-expand' => '\f065', 'fa-compress' => '\f066', 'fa-plus' => '\f067', 'fa-minus' => '\f068', 'fa-asterisk' => '\f069', 'fa-exclamation-circle' => '\f06a', 'fa-gift' => '\f06b', 'fa-leaf' => '\f06c', 'fa-fire' => '\f06d', 'fa-eye' => '\f06e', 'fa-eye-slash' => '\f070', 'fa-exclamation-triangle' => '\f071', 'fa-plane' => '\f072', 'fa-calendar' => '\f073', 'fa-random' => '\f074', 'fa-comment' => '\f075', 'fa-magnet' => '\f076', 'fa-chevron-up' => '\f077', 'fa-chevron-down' => '\f078', 'fa-retweet' => '\f079', 'fa-shopping-cart' => '\f07a', 'fa-folder' => '\f07b', 'fa-folder-open' => '\f07c', 'fa-arrows-v' => '\f07d', 'fa-arrows-h' => '\f07e', 'fa-bar-chart-o' => '\f080', 'fa-twitter-square' => '\f081', 'fa-facebook-square' => '\f082', 'fa-camera-retro' => '\f083', 'fa-key' => '\f084', 'fa-cogs' => '\f085', 'fa-comments' => '\f086', 'fa-thumbs-o-up' => '\f087', 'fa-thumbs-o-down' => '\f088', 'fa-star-half' => '\f089', 'fa-heart-o' => '\f08a', 'fa-sign-out' => '\f08b', 'fa-linkedin-square' => '\f08c', 'fa-thumb-tack' => '\f08d', 'fa-external-link' => '\f08e', 'fa-sign-in' => '\f090', 'fa-trophy' => '\f091', 'fa-github-square' => '\f092', 'fa-upload' => '\f093', 'fa-lemon-o' => '\f094', 'fa-phone' => '\f095', 'fa-square-o' => '\f096', 'fa-bookmark-o' => '\f097', 'fa-phone-square' => '\f098', 'fa-twitter' => '\f099', 'fa-facebook' => '\f09a', 'fa-github' => '\f09b', 'fa-unlock' => '\f09c', 'fa-credit-card' => '\f09d', 'fa-rss' => '\f09e', 'fa-hdd-o' => '\f0a0', 'fa-bullhorn' => '\f0a1', 'fa-bell' => '\f0f3', 'fa-certificate' => '\f0a3', 'fa-hand-o-right' => '\f0a4', 'fa-hand-o-left' => '\f0a5', 'fa-hand-o-up' => '\f0a6', 'fa-hand-o-down' => '\f0a7', 'fa-arrow-circle-left' => '\f0a8', 'fa-arrow-circle-right' => '\f0a9', 'fa-arrow-circle-up' => '\f0aa', 'fa-arrow-circle-down' => '\f0ab', 'fa-globe' => '\f0ac', 'fa-wrench' => '\f0ad', 'fa-tasks' => '\f0ae', 'fa-filter' => '\f0b0', 'fa-briefcase' => '\f0b1', 'fa-arrows-alt' => '\f0b2', 'fa-users' => '\f0c0', 'fa-link' => '\f0c1', 'fa-cloud' => '\f0c2', 'fa-flask' => '\f0c3', 'fa-scissors' => '\f0c4', 'fa-files-o' => '\f0c5', 'fa-paperclip' => '\f0c6', 'fa-floppy-o' => '\f0c7', 'fa-square' => '\f0c8', 'fa-bars' => '\f0c9', 'fa-list-ul' => '\f0ca', 'fa-list-ol' => '\f0cb', 'fa-strikethrough' => '\f0cc', 'fa-underline' => '\f0cd', 'fa-table' => '\f0ce', 'fa-magic' => '\f0d0', 'fa-truck' => '\f0d1', 'fa-pinterest' => '\f0d2', 'fa-pinterest-square' => '\f0d3', 'fa-google-plus-square' => '\f0d4', 'fa-google-plus' => '\f0d5', 'fa-money' => '\f0d6', 'fa-caret-down' => '\f0d7', 'fa-caret-up' => '\f0d8', 'fa-caret-left' => '\f0d9', 'fa-caret-right' => '\f0da', 'fa-columns' => '\f0db', 'fa-sort' => '\f0dc', 'fa-sort-desc' => '\f0dd', 'fa-sort-asc' => '\f0de', 'fa-envelope' => '\f0e0', 'fa-linkedin' => '\f0e1', 'fa-undo' => '\f0e2', 'fa-gavel' => '\f0e3', 'fa-tachometer' => '\f0e4', 'fa-comment-o' => '\f0e5', 'fa-comments-o' => '\f0e6', 'fa-bolt' => '\f0e7', 'fa-sitemap' => '\f0e8', 'fa-umbrella' => '\f0e9', 'fa-clipboard' => '\f0ea', 'fa-lightbulb-o' => '\f0eb', 'fa-exchange' => '\f0ec', 'fa-cloud-download' => '\f0ed', 'fa-cloud-upload' => '\f0ee', 'fa-user-md' => '\f0f0', 'fa-stethoscope' => '\f0f1', 'fa-suitcase' => '\f0f2', 'fa-bell-o' => '\f0a2', 'fa-coffee' => '\f0f4', 'fa-cutlery' => '\f0f5', 'fa-file-text-o' => '\f0f6', 'fa-building-o' => '\f0f7', 'fa-hospital-o' => '\f0f8', 'fa-ambulance' => '\f0f9', 'fa-medkit' => '\f0fa', 'fa-fighter-jet' => '\f0fb', 'fa-beer' => '\f0fc', 'fa-h-square' => '\f0fd', 'fa-plus-square' => '\f0fe', 'fa-angle-double-left' => '\f100', 'fa-angle-double-right' => '\f101', 'fa-angle-double-up' => '\f102', 'fa-angle-double-down' => '\f103', 'fa-angle-left' => '\f104', 'fa-angle-right' => '\f105', 'fa-angle-up' => '\f106', 'fa-angle-down' => '\f107', 'fa-desktop' => '\f108', 'fa-laptop' => '\f109', 'fa-tablet' => '\f10a', 'fa-mobile' => '\f10b', 'fa-circle-o' => '\f10c', 'fa-quote-left' => '\f10d', 'fa-quote-right' => '\f10e', 'fa-spinner' => '\f110', 'fa-circle' => '\f111', 'fa-reply' => '\f112', 'fa-github-alt' => '\f113', 'fa-folder-o' => '\f114', 'fa-folder-open-o' => '\f115', 'fa-smile-o' => '\f118', 'fa-frown-o' => '\f119', 'fa-meh-o' => '\f11a', 'fa-gamepad' => '\f11b', 'fa-keyboard-o' => '\f11c', 'fa-flag-o' => '\f11d', 'fa-flag-checkered' => '\f11e', 'fa-terminal' => '\f120', 'fa-code' => '\f121', 'fa-reply-all' => '\f122', 'fa-star-half-o' => '\f123', 'fa-location-arrow' => '\f124', 'fa-crop' => '\f125', 'fa-code-fork' => '\f126', 'fa-chain-broken' => '\f127', 'fa-question' => '\f128', 'fa-info' => '\f129', 'fa-exclamation' => '\f12a', 'fa-superscript' => '\f12b', 'fa-subscript' => '\f12c', 'fa-eraser' => '\f12d', 'fa-puzzle-piece' => '\f12e', 'fa-microphone' => '\f130', 'fa-microphone-slash' => '\f131', 'fa-shield' => '\f132', 'fa-calendar-o' => '\f133', 'fa-fire-extinguisher' => '\f134', 'fa-rocket' => '\f135', 'fa-maxcdn' => '\f136', 'fa-chevron-circle-left' => '\f137', 'fa-chevron-circle-right' => '\f138', 'fa-chevron-circle-up' => '\f139', 'fa-chevron-circle-down' => '\f13a', 'fa-html5' => '\f13b', 'fa-css3' => '\f13c', 'fa-anchor' => '\f13d', 'fa-unlock-alt' => '\f13e', 'fa-bullseye' => '\f140', 'fa-ellipsis-h' => '\f141', 'fa-ellipsis-v' => '\f142', 'fa-rss-square' => '\f143', 'fa-play-circle' => '\f144', 'fa-ticket' => '\f145', 'fa-minus-square' => '\f146', 'fa-minus-square-o' => '\f147', 'fa-level-up' => '\f148', 'fa-level-down' => '\f149', 'fa-check-square' => '\f14a', 'fa-pencil-square' => '\f14b', 'fa-external-link-square' => '\f14c', 'fa-share-square' => '\f14d', 'fa-compass' => '\f14e', 'fa-caret-square-o-down' => '\f150', 'fa-caret-square-o-up' => '\f151', 'fa-caret-square-o-right' => '\f152', 'fa-eur' => '\f153', 'fa-gbp' => '\f154', 'fa-usd' => '\f155', 'fa-inr' => '\f156', 'fa-jpy' => '\f157', 'fa-rub' => '\f158', 'fa-krw' => '\f159', 'fa-btc' => '\f15a', 'fa-file' => '\f15b', 'fa-file-text' => '\f15c', 'fa-sort-alpha-asc' => '\f15d', 'fa-sort-alpha-desc' => '\f15e', 'fa-sort-amount-asc' => '\f160', 'fa-sort-amount-desc' => '\f161', 'fa-sort-numeric-asc' => '\f162', 'fa-sort-numeric-desc' => '\f163', 'fa-thumbs-up' => '\f164', 'fa-thumbs-down' => '\f165', 'fa-youtube-square' => '\f166', 'fa-youtube' => '\f167', 'fa-xing' => '\f168', 'fa-xing-square' => '\f169', 'fa-youtube-play' => '\f16a', 'fa-dropbox' => '\f16b', 'fa-stack-overflow' => '\f16c', 'fa-instagram' => '\f16d', 'fa-flickr' => '\f16e', 'fa-adn' => '\f170', 'fa-bitbucket' => '\f171', 'fa-bitbucket-square' => '\f172', 'fa-tumblr' => '\f173', 'fa-tumblr-square' => '\f174', 'fa-long-arrow-down' => '\f175', 'fa-long-arrow-up' => '\f176', 'fa-long-arrow-left' => '\f177', 'fa-long-arrow-right' => '\f178', 'fa-apple' => '\f179', 'fa-windows' => '\f17a', 'fa-android' => '\f17b', 'fa-linux' => '\f17c', 'fa-dribbble' => '\f17d', 'fa-skype' => '\f17e', 'fa-foursquare' => '\f180', 'fa-trello' => '\f181', 'fa-female' => '\f182', 'fa-male' => '\f183', 'fa-gittip' => '\f184', 'fa-sun-o' => '\f185', 'fa-moon-o' => '\f186', 'fa-archive' => '\f187', 'fa-bug' => '\f188', 'fa-vk' => '\f189', 'fa-weibo' => '\f18a', 'fa-renren' => '\f18b', 'fa-pagelines' => '\f18c', 'fa-stack-exchange' => '\f18d', 'fa-arrow-circle-o-right' => '\f18e', 'fa-arrow-circle-o-left' => '\f190', 'fa-caret-square-o-left' => '\f191', 'fa-dot-circle-o' => '\f192', 'fa-wheelchair' => '\f193', 'fa-vimeo-square' => '\f194', 'fa-try' => '\f195', 'fa-plus-square-o' => '\f196', 'fa-space-shuttle' => '\f197', 'fa-slack' => '\f198', 'fa-envelope-square' => '\f199', 'fa-wordpress' => '\f19a', 'fa-openid' => '\f19b', 'fa-university' => '\f19c', 'fa-graduation-cap' => '\f19d', 'fa-yahoo' => '\f19e', 'fa-google' => '\f1a0', 'fa-reddit' => '\f1a1', 'fa-reddit-square' => '\f1a2', 'fa-stumbleupon-circle' => '\f1a3', 'fa-stumbleupon' => '\f1a4', 'fa-delicious' => '\f1a5', 'fa-digg' => '\f1a6', 'fa-pied-piper' => '\f1a7', 'fa-pied-piper-alt' => '\f1a8', 'fa-drupal' => '\f1a9', 'fa-joomla' => '\f1aa', 'fa-language' => '\f1ab', 'fa-fax' => '\f1ac', 'fa-building' => '\f1ad', 'fa-child' => '\f1ae', 'fa-paw' => '\f1b0', 'fa-spoon' => '\f1b1', 'fa-cube' => '\f1b2', 'fa-cubes' => '\f1b3', 'fa-behance' => '\f1b4', 'fa-behance-square' => '\f1b5', 'fa-steam' => '\f1b6', 'fa-steam-square' => '\f1b7', 'fa-recycle' => '\f1b8', 'fa-car' => '\f1b9', 'fa-taxi' => '\f1ba', 'fa-tree' => '\f1bb', 'fa-spotify' => '\f1bc', 'fa-deviantart' => '\f1bd', 'fa-soundcloud' => '\f1be', 'fa-database' => '\f1c0', 'fa-file-pdf-o' => '\f1c1', 'fa-file-word-o' => '\f1c2', 'fa-file-excel-o' => '\f1c3', 'fa-file-powerpoint-o' => '\f1c4', 'fa-file-image-o' => '\f1c5', 'fa-file-archive-o' => '\f1c6', 'fa-file-audio-o' => '\f1c7', 'fa-file-video-o' => '\f1c8', 'fa-file-code-o' => '\f1c9', 'fa-vine' => '\f1ca', 'fa-codepen' => '\f1cb', 'fa-jsfiddle' => '\f1cc', 'fa-life-ring' => '\f1cd', 'fa-circle-o-notch' => '\f1ce', 'fa-rebel' => '\f1d0', 'fa-empire' => '\f1d1', 'fa-git-square' => '\f1d2', 'fa-git' => '\f1d3', 'fa-hacker-news' => '\f1d4', 'fa-tencent-weibo' => '\f1d5', 'fa-qq' => '\f1d6', 'fa-weixin' => '\f1d7', 'fa-paper-plane' => '\f1d8', 'fa-paper-plane-o' => '\f1d9', 'fa-history' => '\f1da', 'fa-circle-thin' => '\f1db', 'fa-header' => '\f1dc', 'fa-paragraph' => '\f1dd', 'fa-sliders' => '\f1de', 'fa-share-alt' => '\f1e0', 'fa-share-alt-square' => '\f1e1', 'fa-bomb' => '\f1e2' );
    
    $fie_field = array(
        'pe-7f-cloud-upload','pe-7f-angle-up','pe-7f-cloud-download','pe-7f-angle-right',
        'pe-7f-angle-left','pe-7f-angle-down','pe-7f-wallet','pe-7f-volume2','pe-7f-volume1',
        'pe-7f-voicemail','pe-7f-video', 'pe-7f-user', 'pe-7f-upload','pe-7f-unlock',
        'pe-7f-umbrella','pe-7f-trash','pe-7f-tools','pe-7f-timer','pe-7f-ticket',
        'pe-7f-target','pe-7f-sun','pe-7f-study','pe-7f-stopwatch','pe-7f-star','pe-7f-speaker',
        'pe-7f-signal','pe-7f-shuffle','pe-7f-shopbag','pe-7f-share','pe-7f-server','pe-7f-search',
        'pe-7f-science','pe-7f-ribbon','pe-7f-repeat','pe-7f-refresh','pe-7f-refresh-cloud',
        'pe-7f-radio','pe-7f-print','pe-7f-prev','pe-7f-power','pe-7f-portfolio','pe-7f-plus',
        'pe-7f-play','pe-7f-plane','pe-7f-photo-gallery','pe-7f-phone','pe-7f-pen','pe-7f-paper-plane',
        'pe-7f-bluetooth','pe-7f-paint','pe-7f-wristwatch','pe-7f-notebook','pe-7f-world',
        'pe-7f-note','pe-7f-volume','pe-7f-next','pe-7f-paperclip','pe-7f-news-paper',
        'pe-7f-note2','pe-7f-musiclist','pe-7f-network','pe-7f-music','pe-7f-mouse','pe-7f-cash',
        'pe-7f-more','pe-7f-add-user','pe-7f-moon','pe-7f-way','pe-7f-monitor','pe-7f-bottom-arrow',
        'pe-7f-micro','pe-7f-medal','pe-7f-menu','pe-7f-like2','pe-7f-map','pe-7f-left-arrow',
        'pe-7f-map-marker','pe-7f-key','pe-7f-mail','pe-7f-joy','pe-7f-mail-open',
        'pe-7f-id','pe-7f-mail-open-file','pe-7f-film','pe-7f-magnet','pe-7f-disk',
        'pe-7f-loop','pe-7f-delete-user','pe-7f-look','pe-7f-pin','pe-7f-lock','pe-7f-users',
        'pe-7f-lintern','pe-7f-user-female','pe-7f-link','pe-7f-up-arrow','pe-7f-like','pe-7f-switch',
        'pe-7f-light','pe-7f-scissors','pe-7f-less','pe-7f-safe','pe-7f-keypad','pe-7f-right-arrow',
        'pe-7f-junk','pe-7f-plug','pe-7f-info','pe-7f-mute','pe-7f-home','pe-7f-help2',
        'pe-7f-help1','pe-7f-graph3','pe-7f-graph2','pe-7f-graph1','pe-7f-graph','pe-7f-global',
        'pe-7f-gleam','pe-7f-glasses','pe-7f-gift','pe-7f-folder','pe-7f-flag','pe-7f-filter',
        'pe-7f-file','pe-7f-expand','pe-7f-expand1','pe-7f-edit','pe-7f-drop','pe-7f-drawer',
        'pe-7f-download','pe-7f-display2','pe-7f-display1','pe-7f-diskette','pe-7f-date','pe-7f-cup',
        'pe-7f-culture','pe-7f-crop','pe-7f-credit','pe-7f-copy-file','pe-7f-config','pe-7f-compass',
        'pe-7f-comment','pe-7f-coffee','pe-7f-cloud','pe-7f-clock','pe-7f-check','pe-7f-chat',
        'pe-7f-cart','pe-7f-camera','pe-7f-call','pe-7f-calculator','pe-7f-browser','pe-7f-box1',
        'pe-7f-box','pe-7f-bookmarks','pe-7f-bicycle','pe-7f-bell','pe-7f-battery','pe-7f-ball',
        'pe-7f-back','pe-7f-attention','pe-7f-anchor','pe-7f-albums','pe-7f-alarm','pe-7f-airplay',
        'pe-7f-close'
        
    );
    
    $pie_strok = array(
        'pe-7s-cloud-upload','pe-7s-cash','pe-7s-close','pe-7s-bluetooth','pe-7s-cloud-download','pe-7s-way',
        'pe-7s-close-circle','pe-7s-id','pe-7s-angle-up','pe-7s-wristwatch','pe-7s-angle-up-circle',
        'pe-7s-world','pe-7s-angle-right','pe-7s-volume','pe-7s-angle-right-circle',
        'pe-7s-users','pe-7s-angle-left','pe-7s-user-female','pe-7s-angle-left-circle',
        'pe-7s-up-arrow','pe-7s-angle-down','pe-7s-switch','pe-7s-angle-down-circle',
        'pe-7s-scissors','pe-7s-wallet','pe-7s-safe','pe-7s-volume2','pe-7s-volume1','pe-7s-voicemail',
        'pe-7s-video','pe-7s-user','pe-7s-upload','pe-7s-unlock','pe-7s-umbrella','pe-7s-trash',
        'pe-7s-tools','pe-7s-timer','pe-7s-ticket','pe-7s-target','pe-7s-sun','pe-7s-study',
        'pe-7s-stopwatch','pe-7s-star','pe-7s-speaker','pe-7s-signal','pe-7s-shuffle',
        'pe-7s-shopbag','pe-7s-share','pe-7s-server','pe-7s-search','pe-7s-film',
        'pe-7s-science','pe-7s-disk','pe-7s-ribbon','pe-7s-repeat','pe-7s-refresh',
        'pe-7s-add-user','pe-7s-refresh-cloud','pe-7s-paperclip','pe-7s-radio','pe-7s-note2',
        'pe-7s-print','pe-7s-network','pe-7s-prev','pe-7s-mute','pe-7s-power',
        'pe-7s-medal','pe-7s-portfolio','pe-7s-like2','pe-7s-plus','pe-7s-left-arrow',
        'pe-7s-play','pe-7s-key','pe-7s-plane','pe-7s-joy','pe-7s-photo-gallery',
        'pe-7s-pin','pe-7s-phone','pe-7s-plug','pe-7s-pen','pe-7s-right-arrow',
        'pe-7s-paper-plane','pe-7s-delete-user','pe-7s-paint','pe-7s-bottom-arrow','pe-7s-notebook',
        'pe-7s-note','pe-7s-next','pe-7s-news-paper','pe-7s-musiclist','pe-7s-music',
        'pe-7s-mouse','pe-7s-more','pe-7s-moon','pe-7s-monitor','pe-7s-micro',
        'pe-7s-menu','pe-7s-map','pe-7s-map-marker','pe-7s-mail','pe-7s-mail-open',
        'pe-7s-mail-open-file','pe-7s-magnet','pe-7s-loop','pe-7s-look','pe-7s-lock',
        'pe-7s-lintern','pe-7s-link','pe-7s-like','pe-7s-light','pe-7s-less',
        'pe-7s-keypad','pe-7s-junk','pe-7s-info','pe-7s-home','pe-7s-help2',
        'pe-7s-help1','pe-7s-graph3','pe-7s-graph2','pe-7s-graph1','pe-7s-graph',
        'pe-7s-global','pe-7s-gleam','pe-7s-glasses','pe-7s-gift','pe-7s-folder',
        'pe-7s-flag','pe-7s-filter','pe-7s-file','pe-7s-expand1','pe-7s-exapnd2',
        'pe-7s-edit','pe-7s-drop','pe-7s-drawer','pe-7s-download','pe-7s-display2',
        'pe-7s-display1','pe-7s-diskette','pe-7s-date','pe-7s-cup','pe-7s-culture',
        'pe-7s-crop','pe-7s-credit','pe-7s-copy-file','pe-7s-config','pe-7s-compass',
        'pe-7s-comment','pe-7s-coffee','pe-7s-cloud','pe-7s-clock','pe-7s-check',
        'pe-7s-chat','pe-7s-cart','pe-7s-camera','pe-7s-call','pe-7s-calculator',
        'pe-7s-browser','pe-7s-box2','pe-7s-box1','pe-7s-bookmarks','pe-7s-bicycle',
        'pe-7s-bell','pe-7s-battery','pe-7s-ball','pe-7s-back','pe-7s-attention',
        'pe-7s-anchor','pe-7s-albums','pe-7s-alarm','pe-7s-airplay'
        
    );
    
    $esen_77 = array(
        'esen-Plus', 'esen-Attachment', 'esen-Reply', 'esen-BarGraph', 'esen-Book','esen-Bookmark',
        'esen-Briefcase','esen-BrowserWindow','esen-Calendar','esen-Camera','esen-Cancel','esen-Clock',
        'esen-CommentwithLines','esen-Comment','esen-Computer','esen-Controls','esen-Conversation','esen-CreditCard',
        'esen-Crosshair','esen-Diary','esen-DownArrow','esen-Email','esen-Folder','esen-Forward','esen-Heart',
        'esen-Home','esen-Inbox','esen-Layers','esen-LeftArrow','esen-Link','esen-List','esen-LocationMarker',
        'esen-Location','esen-Map','esen-Medal','esen-Menu','esen-Microphone','esen-Minus','esen-Options','esen-MoreOptions',
        'esen-Music','esen-Mute','esen-Notification','esen-Padlock','esen-Document','esen-Phone','esen-Photo','esen-PieChart',
        'esen-Pin','esen-View','esen-Printer','esen-Profile','esen-Rearrange','esen-Refresh','esen-RightArrow','esen-Save',
        'esen-Search','esen-Settings','esen-Share','esen-Shop','esen-Signals','esen-Signal','esen-Volume','esen-Star',
        'esen-iPad','esen-Tag','esen-Checkmark','esen-Toggle','esen-Trash','esen-Typing','esen-UpArrow','esen-User','esen-Users',
        'esen-VideoCamera','esen-Video','esen-Warning','esen-CreateNew'
        );
    
    $strock = array(
        'sgi-WorldWide', 'sgi-WorldGlobe', 'sgi-Underpants', 'sgi-Tshirt', 'sgi-Trousers', 'sgi-Tie', 
        'sgi-TennisBall', 'sgi-Telesocpe', 'sgi-Stop', 'sgi-Starship', 'sgi-Starship2', 'sgi-Speaker', 
        'sgi-Speaker2', 'sgi-Soccer', 'sgi-Snikers', 'sgi-Scisors', 'sgi-Puzzle', 'sgi-Printer', 
        'sgi-Pool', 'sgi-Podium', 'sgi-Play', 'sgi-Planet', 'sgi-Pause', 'sgi-Next', 
        'sgi-MusicNote2', 'sgi-MusicNote', 'sgi-MusicMixer', 'sgi-Microphone', 'sgi-Medal', 'sgi-ManFigure', 
        'sgi-Magnet', 'sgi-Like', 'sgi-Hanger', 'sgi-Handicap', 'sgi-Forward', 'sgi-Footbal', 
        'sgi-Flag', 'sgi-FemaleFigure', 'sgi-Dislike', 'sgi-DiamondRing', 'sgi-Cup', 'sgi-Crown', 
        'sgi-Column', 'sgi-Click', 'sgi-Cassette', 'sgi-Bomb', 'sgi-BatteryLow', 'sgi-BatteryFull', 
        'sgi-Bascketball', 'sgi-Astronaut', 'sgi-WineGlass', 'sgi-Water', 'sgi-Wallet', 'sgi-Umbrella', 
        'sgi-TV', 'sgi-TeaMug', 'sgi-Tablet', 'sgi-Soda', 'sgi-SodaCan', 'sgi-SimCard', 
        'sgi-Signal', 'sgi-Shaker', 'sgi-Radio', 'sgi-Pizza', 'sgi-Phone', 'sgi-Notebook', 
        'sgi-Mug', 'sgi-Mastercard', 'sgi-Ipod', 'sgi-Info', 'sgi-Icecream2', 'sgi-Icecream1', 
        'sgi-Hourglass', 'sgi-Help', 'sgi-Goto', 'sgi-Glasses', 'sgi-Gameboy', 'sgi-ForkandKnife', 
        'sgi-Export', 'sgi-Exit', 'sgi-Espresso', 'sgi-Drop', 'sgi-Download', 'sgi-Dollars', 
        'sgi-Dollar', 'sgi-DesktopMonitor', 'sgi-Corkscrew', 'sgi-CoffeeToGo', 'sgi-Chart', 'sgi-ChartUp', 
        'sgi-ChartDown', 'sgi-Calculator', 'sgi-Bread', 'sgi-Bourbon', 'sgi-BottleofWIne', 'sgi-Bag', 
        'sgi-Arrow', 'sgi-Antenna2', 'sgi-Antenna1', 'sgi-Anchor', 'sgi-Wheelbarrow', 'sgi-Webcam', 
        'sgi-Unlinked', 'sgi-Truck', 'sgi-Timer', 'sgi-Time', 'sgi-StorageBox', 'sgi-Star', 
        'sgi-ShoppingCart', 'sgi-Shield', 'sgi-Seringe', 'sgi-Pulse', 'sgi-Plaster', 'sgi-Plaine', 
        'sgi-Pill', 'sgi-PicnicBasket', 'sgi-Phone2', 'sgi-Pencil', 'sgi-Pen', 'sgi-PaperClip', 
        'sgi-On-Off', 'sgi-Mouse', 'sgi-Megaphone', 'sgi-Linked', 'sgi-Keyboard', 'sgi-House', 
        'sgi-Heart', 'sgi-Headset', 'sgi-FullShoppingCart', 'sgi-FullScreen', 'sgi-Folder', 'sgi-Floppy', 
        'sgi-Files', 'sgi-File', 'sgi-FileBox', 'sgi-ExitFullScreen', 'sgi-EmptyBox', 'sgi-Delete', 
        'sgi-Controller', 'sgi-Compass', 'sgi-CompassTool', 'sgi-ClipboardText', 'sgi-ClipboardChart', 'sgi-ChemicalGlass', 
        'sgi-CD', 'sgi-Carioca', 'sgi-Car', 'sgi-Book', 'sgi-BigTruck', 'sgi-Bicycle', 
        'sgi-Wrench', 'sgi-Web', 'sgi-Watch', 'sgi-Volume', 'sgi-Video', 'sgi-Users', 
        'sgi-User', 'sgi-UploadCLoud', 'sgi-Typing', 'sgi-Tools', 'sgi-Tag', 'sgi-Speedometter', 
        'sgi-Share', 'sgi-Settings', 'sgi-Search', 'sgi-Screwdriver', 'sgi-Rolodex', 'sgi-Ringer', 
        'sgi-Resume', 'sgi-Restart', 'sgi-PowerOff', 'sgi-Pointer', 'sgi-Picture', 'sgi-OpenedLock', 
        'sgi-Notes', 'sgi-Mute', 'sgi-Movie', 'sgi-Microphone2', 'sgi-Message', 'sgi-MessageRight', 
        'sgi-MessageLeft', 'sgi-Menu', 'sgi-Media', 'sgi-Mail', 'sgi-List', 'sgi-Layers', 
        'sgi-Key', 'sgi-Imbox', 'sgi-Eye', 'sgi-Edit', 'sgi-DSLRCamera', 'sgi-DownloadCloud', 
        'sgi-CompactCamera', 'sgi-Cloud', 'sgi-ClosedLock', 'sgi-Chart2', 'sgi-Bulb', 'sgi-Briefcase', 
        'sgi-Blog', 'sgi-Agenda'
    );
    
    
    $metarial = array(
        'zmdi-3d-rotation', 'zmdi-airplane-off', 'zmdi-airplane', 'zmdi-album', 'zmdi-archive', 'zmdi-assignment-account',
        'zmdi-assignment-alert', 'zmdi-assignment-check', 'zmdi-assignment-o', 'zmdi-assignment-return', 'zmdi-assignment-returned', 'zmdi-assignment',
        'zmdi-attachment-alt', 'zmdi-attachment', 'zmdi-audio', 'zmdi-badge-check', 'zmdi-balance-wallet', 'zmdi-balance',
        'zmdi-battery-alert', 'zmdi-battery-flash', 'zmdi-battery-unknown', 'zmdi-battery', 'zmdi-bike', 'zmdi-block-alt',
        'zmdi-block', 'zmdi-boat', 'zmdi-book-image', 'zmdi-book', 'zmdi-bookmark-outline', 'zmdi-bookmark',
        'zmdi-brush', 'zmdi-bug', 'zmdi-bus', 'zmdi-cake', 'zmdi-car-taxi', 'zmdi-car-wash',
        'zmdi-car', 'zmdi-card-giftcard', 'zmdi-card-membership', 'zmdi-card-travel', 'zmdi-card', 'zmdi-case-check',
        'zmdi-case-download', 'zmdi-case-play', 'zmdi-case', 'zmdi-cast-connected', 'zmdi-cast', 'zmdi-chart-donut',
        'zmdi-chart', 'zmdi-city-alt', 'zmdi-city', 'zmdi-close-circle-o', 'zmdi-close-circle', 'zmdi-close',
        'zmdi-cocktail', 'zmdi-code-setting', 'zmdi-code-smartphone', 'zmdi-code', 'zmdi-coffee', 'zmdi-collection-bookmark',
        'zmdi-collection-case-play', 'zmdi-collection-folder-image', 'zmdi-collection-image-o', 'zmdi-collection-image', 'zmdi-collection-item-1', 'zmdi-collection-item-2',
        'zmdi-collection-item-3', 'zmdi-collection-item-4', 'zmdi-collection-item-5', 'zmdi-collection-item-6', 'zmdi-collection-item-7', 'zmdi-collection-item-8',
        'zmdi-collection-item-9-plus', 'zmdi-collection-item-9', 'zmdi-collection-item', 'zmdi-collection-music', 'zmdi-collection-pdf', 'zmdi-collection-plus',
        'zmdi-collection-speaker', 'zmdi-collection-text', 'zmdi-collection-video', 'zmdi-compass', 'zmdi-cutlery', 'zmdi-delete',
        'zmdi-dialpad', 'zmdi-dns', 'zmdi-drink', 'zmdi-edit', 'zmdi-email-open', 'zmdi-email',
        'zmdi-eye-off', 'zmdi-eye', 'zmdi-eyedropper', 'zmdi-favorite-outline', 'zmdi-favorite', 'zmdi-filter-list',
        'zmdi-fire', 'zmdi-flag', 'zmdi-flare', 'zmdi-flash-auto', 'zmdi-flash-off', 'zmdi-flash',
        'zmdi-flip', 'zmdi-flower-alt', 'zmdi-flower', 'zmdi-font', 'zmdi-fullscreen-alt', 'zmdi-fullscreen-exit',
        'zmdi-fullscreen', 'zmdi-functions', 'zmdi-gas-station', 'zmdi-gesture', 'zmdi-globe-alt', 'zmdi-globe-lock',
        'zmdi-globe', 'zmdi-graduation-cap', 'zmdi-home', 'zmdi-hospital-alt', 'zmdi-hospital', 'zmdi-hotel',
        'zmdi-hourglass-alt', 'zmdi-hourglass-outline', 'zmdi-hourglass', 'zmdi-http', 'zmdi-image-alt', 'zmdi-image-o',
        'zmdi-image', 'zmdi-inbox', 'zmdi-invert-colors-off', 'zmdi-invert-colors', 'zmdi-key', 'zmdi-label-alt-outline',
        'zmdi-label-alt', 'zmdi-label-heart', 'zmdi-label', 'zmdi-labels', 'zmdi-lamp', 'zmdi-landscape',
        'zmdi-layers-off', 'zmdi-layers', 'zmdi-library', 'zmdi-link', 'zmdi-lock-open', 'zmdi-lock-outline',
        'zmdi-lock', 'zmdi-mail-reply-all', 'zmdi-mail-reply', 'zmdi-mail-send', 'zmdi-mall', 'zmdi-map',
        'zmdi-menu', 'zmdi-money-box', 'zmdi-money-off', 'zmdi-money', 'zmdi-more-vert', 'zmdi-more',
        'zmdi-movie-alt', 'zmdi-movie', 'zmdi-nature-people', 'zmdi-nature', 'zmdi-navigation', 'zmdi-open-in-browser',
        'zmdi-open-in-new', 'zmdi-palette', 'zmdi-parking', 'zmdi-pin-account', 'zmdi-pin-assistant', 'zmdi-pin-drop',
        'zmdi-pin-help', 'zmdi-pin-off', 'zmdi-pin', 'zmdi-pizza', 'zmdi-plaster', 'zmdi-power-setting',
        'zmdi-power', 'zmdi-print', 'zmdi-puzzle-piece', 'zmdi-quote', 'zmdi-railway', 'zmdi-receipt',
        'zmdi-refresh-alt', 'zmdi-refresh-sync-alert', 'zmdi-refresh-sync-off', 'zmdi-refresh-sync', 'zmdi-refresh', 'zmdi-roller',
        'zmdi-ruler', 'zmdi-scissors', 'zmdi-screen-rotation-lock', 'zmdi-screen-rotation', 'zmdi-search-for', 'zmdi-search-in-file',
        'zmdi-search-in-page', 'zmdi-search-replace', 'zmdi-search', 'zmdi-seat', 'zmdi-settings-square', 'zmdi-settings',
        'zmdi-shield-check', 'zmdi-shield-security', 'zmdi-shopping-basket', 'zmdi-shopping-cart-plus', 'zmdi-shopping-cart', 'zmdi-sign-in',
        'zmdi-sort-amount-asc', 'zmdi-sort-amount-desc', 'zmdi-sort-asc', 'zmdi-sort-desc', 'zmdi-spellcheck', 'zmdi-storage',
        'zmdi-store-24', 'zmdi-store', 'zmdi-subway', 'zmdi-sun', 'zmdi-tab-unselected', 'zmdi-tab',
        'zmdi-tag-close', 'zmdi-tag-more', 'zmdi-tag', 'zmdi-thumb-down', 'zmdi-thumb-up-down', 'zmdi-thumb-up',
        'zmdi-ticket-star', 'zmdi-toll', 'zmdi-toys', 'zmdi-traffic', 'zmdi-translate', 'zmdi-triangle-down',
        'zmdi-triangle-up', 'zmdi-truck', 'zmdi-turning-sign', 'zmdi-wallpaper', 'zmdi-washing-machine', 'zmdi-window-maximize',
        'zmdi-window-minimize', 'zmdi-window-restore', 'zmdi-wrench', 'zmdi-zoom-in', 'zmdi-zoom-out', 'zmdi-alert-circle-o',
        'zmdi-alert-circle', 'zmdi-alert-octagon', 'zmdi-alert-polygon', 'zmdi-alert-triangle', 'zmdi-help-outline', 'zmdi-help',
        'zmdi-info-outline', 'zmdi-info', 'zmdi-notifications-active', 'zmdi-notifications-add', 'zmdi-notifications-none', 'zmdi-notifications-off',
        'zmdi-notifications-paused', 'zmdi-notifications', 'zmdi-account-add', 'zmdi-account-box-mail', 'zmdi-account-box-o', 'zmdi-account-box-phone',
        'zmdi-account-box', 'zmdi-account-calendar', 'zmdi-account-circle', 'zmdi-account-o', 'zmdi-account', 'zmdi-accounts-add',
        'zmdi-accounts-alt', 'zmdi-accounts-list-alt', 'zmdi-accounts-list', 'zmdi-accounts-outline', 'zmdi-accounts', 'zmdi-face',
        'zmdi-female', 'zmdi-male-alt', 'zmdi-male-female', 'zmdi-male', 'zmdi-mood-bad', 'zmdi-mood',
        'zmdi-run', 'zmdi-walk', 'zmdi-cloud-box', 'zmdi-cloud-circle', 'zmdi-cloud-done', 'zmdi-cloud-download',
        'zmdi-cloud-off', 'zmdi-cloud-outline-alt', 'zmdi-cloud-outline', 'zmdi-cloud-upload', 'zmdi-cloud', 'zmdi-download',
        'zmdi-file-plus', 'zmdi-file-text', 'zmdi-file', 'zmdi-folder-outline', 'zmdi-folder-person', 'zmdi-folder-star-alt',
        'zmdi-folder-star', 'zmdi-folder', 'zmdi-gif', 'zmdi-upload', 'zmdi-border-all', 'zmdi-border-bottom',
        'zmdi-border-clear', 'zmdi-border-color', 'zmdi-border-horizontal', 'zmdi-border-inner', 'zmdi-border-left', 'zmdi-border-outer',
        'zmdi-border-right', 'zmdi-border-style', 'zmdi-border-top', 'zmdi-border-vertical', 'zmdi-copy', 'zmdi-crop',
        'zmdi-format-align-center', 'zmdi-format-align-justify', 'zmdi-format-align-left', 'zmdi-format-align-right', 'zmdi-format-bold', 'zmdi-format-clear-all',
        'zmdi-format-clear', 'zmdi-format-color-fill', 'zmdi-format-color-reset', 'zmdi-format-color-text', 'zmdi-format-indent-increase', 'zmdi-format-italic',
        'zmdi-format-line-spacing', 'zmdi-format-list-bulleted', 'zmdi-format-list-numbered', 'zmdi-format-ltr', 'zmdi-format-rtl', 'zmdi-format-size',
        'zmdi-format-strikethrough-s', 'zmdi-format-strikethrough', 'zmdi-format-subject', 'zmdi-format-underlined', 'zmdi-format-valign-bottom', 'zmdi-format-valign-center',
        'zmdi-format-valign-top', 'zmdi-redo', 'zmdi-select-all', 'zmdi-space-bar', 'zmdi-text-format', 'zmdi-transform',
        'zmdi-undo', 'zmdi-wrap-text', 'zmdi-comment-alert', 'zmdi-comment-alt-text', 'zmdi-comment-alt', 'zmdi-comment-edit',
        'zmdi-comment-image', 'zmdi-comment-list', 'zmdi-comment-more', 'zmdi-comment-outline', 'zmdi-comment-text-alt', 'zmdi-comment-text',
        'zmdi-comment-video', 'zmdi-comment', 'zmdi-comments', 'zmdi-check-all', 'zmdi-check-circle-u', 'zmdi-check-circle',
        'zmdi-check-square', 'zmdi-check', 'zmdi-circle-o', 'zmdi-circle', 'zmdi-dot-circle-alt', 'zmdi-dot-circle',
        'zmdi-minus-circle-outline', 'zmdi-minus-circle', 'zmdi-minus-square', 'zmdi-minus', 'zmdi-plus-circle-o-duplicate', 'zmdi-plus-circle-o',
        'zmdi-plus-circle', 'zmdi-plus-square', 'zmdi-plus', 'zmdi-square-o', 'zmdi-star-circle', 'zmdi-star-half',
        'zmdi-star-outline', 'zmdi-star', 'zmdi-bluetooth-connected', 'zmdi-bluetooth-off', 'zmdi-bluetooth-search', 'zmdi-bluetooth-setting',
        'zmdi-bluetooth', 'zmdi-camera-add', 'zmdi-camera-alt', 'zmdi-camera-bw', 'zmdi-camera-front', 'zmdi-camera-mic',
        'zmdi-camera-party-mode', 'zmdi-camera-rear', 'zmdi-camera-roll', 'zmdi-camera-switch', 'zmdi-camera', 'zmdi-card-alert','zmdi-card-off','zmdi-card-sd',
        'zmdi-card-sim', 'zmdi-desktop-mac', 'zmdi-desktop-windows', 'zmdi-device-hub', 'zmdi-devices-off', 'zmdi-devices','zmdi-dock','zmdi-floppy',
        'zmdi-gamepad', 'zmdi-gps-dot', 'zmdi-gps-off', 'zmdi-gps', 'zmdi-headset-mic', 'zmdi-headset','zmdi-input-antenna','zmdi-input-composite',
        'zmdi-input-hdmi', 'zmdi-input-power', 'zmdi-input-svideo', 'zmdi-keyboard-hide', 'zmdi-keyboard', 'zmdi-laptop-chromebook',
        'zmdi-laptop-mac', 'zmdi-laptop', 'zmdi-mic-off', 'zmdi-mic-outline', 'zmdi-mic-setting', 'zmdi-mic','zmdi-mouse','zmdi-network-alert',
        'zmdi-network-locked', 'zmdi-network-off', 'zmdi-network-outline', 'zmdi-network-setting', 'zmdi-network', 'zmdi-phone-bluetooth',
        'zmdi-phone-end', 'zmdi-phone-forwarded', 'zmdi-phone-in-talk', 'zmdi-phone-locked', 'zmdi-phone-missed', 'zmdi-phone-msg',
        'zmdi-phone-paused', 'zmdi-phone-ring', 'zmdi-phone-setting', 'zmdi-phone-sip', 'zmdi-phone', 'zmdi-portable-wifi-changes',
        'zmdi-portable-wifi-off', 'zmdi-portable-wifi', 'zmdi-radio', 'zmdi-reader', 'zmdi-remote-control-alt', 'zmdi-remote-control',
        'zmdi-router', 'zmdi-scanner', 'zmdi-smartphone-android', 'zmdi-smartphone-download', 'zmdi-smartphone-erase', 'zmdi-smartphone-info',
        'zmdi-smartphone-iphone', 'zmdi-smartphone-landscape-lock', 'zmdi-smartphone-landscape', 'zmdi-smartphone-lock', 'zmdi-smartphone-portrait-lock', 'zmdi-smartphone-ring',
        'zmdi-smartphone-setting', 'zmdi-smartphone-setup', 'zmdi-smartphone', 'zmdi-speaker', 'zmdi-tablet-android', 'zmdi-tablet-mac',
        'zmdi-tablet', 'zmdi-tv-alt-play', 'zmdi-tv-list', 'zmdi-tv-play', 'zmdi-tv', 'zmdi-usb','zmdi-videocam-off','zmdi-videocam-switch','zmdi-videocam','zmdi-watch',
        'zmdi-wifi-alt-2', 'zmdi-wifi-alt', 'zmdi-wifi-info', 'zmdi-wifi-lock', 'zmdi-wifi-off', 'zmdi-wifi-outline',
        'zmdi-wifi', 'zmdi-arrow-left-bottom', 'zmdi-arrow-left', 'zmdi-arrow-merge', 'zmdi-arrow-missed', 'zmdi-arrow-right-top',
        'zmdi-arrow-right', 'zmdi-arrow-split', 'zmdi-arrows', 'zmdi-caret-down-circle', 'zmdi-caret-down', 'zmdi-caret-left-circle',
        'zmdi-caret-left', 'zmdi-caret-right-circle', 'zmdi-caret-right', 'zmdi-caret-up-circle', 'zmdi-caret-up', 'zmdi-chevron-down',
        'zmdi-chevron-left', 'zmdi-chevron-right', 'zmdi-chevron-up', 'zmdi-long-arrow-down', 'zmdi-long-arrow-left', 'zmdi-long-arrow-return',
        'zmdi-long-arrow-right', 'zmdi-long-arrow-tab', 'zmdi-long-arrow-up', 'zmdi-rotate-ccw', 'zmdi-rotate-cw', 'zmdi-rotate-left',
        'zmdi-rotate-right', 'zmdi-square-down', 'zmdi-square-right', 'zmdi-swap-alt', 'zmdi-swap-vertical-circle', 'zmdi-swap-vertical',
        'zmdi-swap', 'zmdi-trending-down', 'zmdi-trending-flat', 'zmdi-trending-up', 'zmdi-unfold-less', 'zmdi-unfold-more',
        'zmdi-apps', 'zmdi-grid-off', 'zmdi-grid', 'zmdi-view-agenda', 'zmdi-view-array', 'zmdi-view-carousel','zmdi-view-column','zmdi-view-comfy','zmdi-view-compact',
        'zmdi-view-dashboard', 'zmdi-view-day', 'zmdi-view-headline', 'zmdi-view-list-alt', 'zmdi-view-list', 'zmdi-view-module',
        'zmdi-view-quilt', 'zmdi-view-stream', 'zmdi-view-subtitles', 'zmdi-view-toc', 'zmdi-view-web', 'zmdi-view-week',
        'zmdi-widgets', 'zmdi-alarm-check', 'zmdi-alarm-off', 'zmdi-alarm-plus', 'zmdi-alarm-snooze', 'zmdi-alarm',
        'zmdi-calendar-alt', 'zmdi-calendar-check', 'zmdi-calendar-close', 'zmdi-calendar-note', 'zmdi-calendar', 'zmdi-time-countdown',
        'zmdi-time-interval', 'zmdi-time-restore-setting', 'zmdi-time-restore', 'zmdi-time', 'zmdi-timer-off', 'zmdi-timer',
        'zmdi-android-alt', 'zmdi-android', 'zmdi-apple', 'zmdi-behance', 'zmdi-codepen', 'zmdi-dribbble','zmdi-dropbox','zmdi-evernote',
        'zmdi-facebook-box', 'zmdi-facebook', 'zmdi-github-box', 'zmdi-github', 'zmdi-google-drive', 'zmdi-google-earth',
        'zmdi-google-glass', 'zmdi-google-maps', 'zmdi-google-pages', 'zmdi-google-play', 'zmdi-google-plus-box', 'zmdi-google-plus',
        'zmdi-google', 'zmdi-instagram', 'zmdi-language-css3', 'zmdi-language-html5', 'zmdi-language-javascript', 'zmdi-language-python-alt',
        'zmdi-language-python', 'zmdi-lastfm', 'zmdi-linkedin-box', 'zmdi-paypal', 'zmdi-pinterest-box', 'zmdi-pocket',
        'zmdi-polymer', 'zmdi-share', 'zmdi-stack-overflow', 'zmdi-steam-square', 'zmdi-steam', 'zmdi-twitter-box',
        'zmdi-twitter', 'zmdi-vk', 'zmdi-wikipedia', 'zmdi-windows', 'zmdi-aspect-ratio-alt', 'zmdi-aspect-ratio','zmdi-blur-circular','zmdi-blur-linear','zmdi-blur-off',
        'zmdi-blur', 'zmdi-brightness-2', 'zmdi-brightness-3', 'zmdi-brightness-4', 'zmdi-brightness-5', 'zmdi-brightness-6',
        'zmdi-brightness-7', 'zmdi-brightness-auto', 'zmdi-brightness-setting', 'zmdi-broken-image', 'zmdi-center-focus-strong', 'zmdi-center-focus-weak',
        'zmdi-compare', 'zmdi-crop-16-9', 'zmdi-crop-3-2', 'zmdi-crop-5-4', 'zmdi-crop-7-5', 'zmdi-crop-din','zmdi-crop-free','zmdi-crop-landscape',
        'zmdi-crop-portrait', 'zmdi-crop-square', 'zmdi-exposure-alt', 'zmdi-exposure', 'zmdi-filter-b-and-w', 'zmdi-filter-center-focus',
        'zmdi-filter-frames', 'zmdi-filter-tilt-shift', 'zmdi-gradient', 'zmdi-grain', 'zmdi-graphic-eq', 'zmdi-hdr-off',
        'zmdi-hdr-strong', 'zmdi-hdr-weak', 'zmdi-hdr', 'zmdi-iridescent', 'zmdi-leak-off', 'zmdi-leak','zmdi-looks','zmdi-loupe',
        'zmdi-panorama-horizontal', 'zmdi-panorama-vertical', 'zmdi-panorama-wide-angle', 'zmdi-photo-size-select-large', 'zmdi-photo-size-select-small', 'zmdi-picture-in-picture',
        'zmdi-slideshow', 'zmdi-texture', 'zmdi-tonality', 'zmdi-vignette', 'zmdi-wb-auto', 'zmdi-eject-alt','zmdi-eject',
        'zmdi-equalizer', 'zmdi-fast-forward', 'zmdi-fast-rewind', 'zmdi-forward-10', 'zmdi-forward-30', 'zmdi-forward-5',
        'zmdi-hearing', 'zmdi-pause-circle-outline', 'zmdi-pause-circle', 'zmdi-pause', 'zmdi-play-circle-outline', 'zmdi-play-circle',
        'zmdi-play', 'zmdi-play', 'zmdi-playlist-audio', 'zmdi-playlist-plus', 'zmdi-repeat-one', 'zmdi-repeat','zmdi-replay-10','zmdi-replay-30',
        'zmdi-replay-5', 'zmdi-replay', 'zmdi-shuffle', 'zmdi-skip-next', 'zmdi-skip-previous', 'zmdi-stop','zmdi-surround-sound','zmdi-tune',
        'zmdi-volume-down', 'zmdi-volume-mute', 'zmdi-volume-off', 'zmdi-volume-up', 'zmdi-n-1-square', 'zmdi-n-2-square',
        'zmdi-n-3-square', 'zmdi-n-4-square', 'zmdi-n-5-square', 'zmdi-n-6-square', 'zmdi-neg-1', 'zmdi-neg-2',
        'zmdi-plus-1', 'zmdi-plus-2', 'zmdi-sec-10', 'zmdi-sec-3', 'zmdi-zero', 'zmdi-airline-seat-flat-angled','zmdi-airline-seat-flat','zmdi-airline-seat-individual-suite',
        'zmdi-airline-seat-legroom-extra', 'zmdi-airline-seat-legroom-normal', 'zmdi-airline-seat-legroom-reduced', 'zmdi-airline-seat-recline-extra', 'zmdi-airline-seat-recline-normal', 'zmdi-airplay',
        'zmdi-closed-caption', 'zmdi-confirmation-number', 'zmdi-developer-board', 'zmdi-disc-full', 'zmdi-explicit', 'zmdi-flight-land',
        'zmdi-flight-takeoff', 'zmdi-flip-to-back', 'zmdi-flip-to-front', 'zmdi-group-work', 'zmdi-hd', 'zmdi-hq',
        'zmdi-markunread-mailbox', 'zmdi-memory', 'zmdi-nfc', 'zmdi-play-for-work', 'zmdi-power-input', 'zmdi-present-to-all','zmdi-satellite',
        'zmdi-tap-and-play', 'zmdi-vibration', 'zmdi-voicemail', 'zmdi-3d-rotation', 'zmdi-airplane-off', 'zmdi-airplane',
        'zmdi-album', 'zmdi-archive', 'zmdi-assignment-account', 'zmdi-assignment-alert', 'zmdi-assignment-check', 'zmdi-assignment-o',
        'zmdi-assignment-return', 'zmdi-assignment-returned', 'zmdi-assignment', 'zmdi-attachment-alt', 'zmdi-attachment', 'zmdi-audio',
        'zmdi-badge-check', 'zmdi-balance-wallet', 'zmdi-balance', 'zmdi-battery-alert', 'zmdi-battery-flash', 'zmdi-battery-unknown',
        'zmdi-battery', 'zmdi-bike', 'zmdi-block-alt', 'zmdi-block', 'zmdi-boat', 'zmdi-book-image',
        'zmdi-book', 'zmdi-bookmark-outline', 'zmdi-bookmark', 'zmdi-brush', 'zmdi-bug', 'zmdi-bus',
        'zmdi-cake', 'zmdi-car-taxi', 'zmdi-car-wash', 'zmdi-car', 'zmdi-card-giftcard', 'zmdi-card-membership',
        'zmdi-card-travel', 'zmdi-card', 'zmdi-case-check', 'zmdi-case-download', 'zmdi-case-play', 'zmdi-case',
        'zmdi-cast-connected', 'zmdi-cast', 'zmdi-chart-donut', 'zmdi-chart', 'zmdi-city-alt', 'zmdi-city',
        'zmdi-close-circle-o', 'zmdi-close-circle', 'zmdi-close', 'zmdi-cocktail', 'zmdi-code-setting', 'zmdi-code-smartphone',
        'zmdi-code', 'zmdi-coffee', 'zmdi-collection-bookmark', 'zmdi-collection-case-play', 'zmdi-collection-folder-image', 'zmdi-collection-image-o',
        'zmdi-collection-image', 'zmdi-collection-item-1', 'zmdi-collection-item-2', 'zmdi-collection-item-3', 'zmdi-collection-item-4', 'zmdi-collection-item-5',
        'zmdi-collection-item-6', 'zmdi-collection-item-7', 'zmdi-collection-item-8', 'zmdi-collection-item-9-plus', 'zmdi-collection-item-9', 'zmdi-collection-item',
        'zmdi-collection-music', 'zmdi-collection-pdf', 'zmdi-collection-plus', 'zmdi-collection-speaker', 'zmdi-collection-text', 'zmdi-collection-video',
        'zmdi-compass', 'zmdi-cutlery', 'zmdi-delete', 'zmdi-dialpad', 'zmdi-dns', 'zmdi-drink','zmdi-edit','zmdi-email-open','zmdi-email',
        'zmdi-eye-off', 'zmdi-eye', 'zmdi-eyedropper', 'zmdi-favorite-outline', 'zmdi-favorite', 'zmdi-filter-list','zmdi-fire','zmdi-flag','zmdi-flare',
        'zmdi-flash-auto', 'zmdi-flash-off', 'zmdi-flash', 'zmdi-flip', 'zmdi-flower-alt', 'zmdi-flower',
        'zmdi-font', 'zmdi-fullscreen-alt', 'zmdi-fullscreen-exit', 'zmdi-fullscreen', 'zmdi-functions', 'zmdi-gas-station',
        'zmdi-gesture', 'zmdi-globe-alt', 'zmdi-globe-lock', 'zmdi-globe', 'zmdi-graduation-cap', 'zmdi-home',
        'zmdi-hospital-alt', 'zmdi-hospital', 'zmdi-hotel', 'zmdi-hourglass-alt', 'zmdi-hourglass-outline', 'zmdi-hourglass',
        'zmdi-http', 'zmdi-image-alt', 'zmdi-image-o', 'zmdi-image', 'zmdi-inbox', 'zmdi-invert-colors-off',
        'zmdi-invert-colors', 'zmdi-key', 'zmdi-label-alt-outline', 'zmdi-label-alt', 'zmdi-label-heart', 'zmdi-label',
        'zmdi-labels', 'zmdi-lamp', 'zmdi-landscape', 'zmdi-layers-off', 'zmdi-layers', 'zmdi-library',
        'zmdi-link', 'zmdi-lock-open', 'zmdi-lock-outline', 'zmdi-lock', 'zmdi-mail-reply-all', 'zmdi-mail-reply',
        'zmdi-mail-send', 'zmdi-mall', 'zmdi-map', 'zmdi-menu', 'zmdi-money-box', 'zmdi-money-off',
        'zmdi-money', 'zmdi-more-vert', 'zmdi-more', 'zmdi-movie-alt', 'zmdi-movie', 'zmdi-nature-people',
        'zmdi-nature', 'zmdi-navigation', 'zmdi-open-in-browser', 'zmdi-open-in-new', 'zmdi-palette', 'zmdi-parking',
        'zmdi-pin-account', 'zmdi-pin-assistant', 'zmdi-pin-drop', 'zmdi-pin-help', 'zmdi-pin-off', 'zmdi-pin',
        'zmdi-pizza', 'zmdi-plaster', 'zmdi-power-setting', 'zmdi-power', 'zmdi-print', 'zmdi-puzzle-piece',
        'zmdi-quote', 'zmdi-railway', 'zmdi-receipt', 'zmdi-refresh-alt', 'zmdi-refresh-sync-alert', 'zmdi-refresh-sync-off',
        'zmdi-refresh-sync', 'zmdi-refresh', 'zmdi-roller', 'zmdi-ruler', 'zmdi-scissors', 'zmdi-screen-rotation-lock',
        'zmdi-screen-rotation', 'zmdi-search-for', 'zmdi-search-in-file', 'zmdi-search-in-page', 'zmdi-search-replace', 'zmdi-search',
        'zmdi-seat', 'zmdi-settings-square', 'zmdi-settings', 'zmdi-shield-check', 'zmdi-shield-security', 'zmdi-shopping-basket',
        'zmdi-shopping-cart-plus', 'zmdi-shopping-cart', 'zmdi-sign-in', 'zmdi-sort-amount-asc', 'zmdi-sort-amount-desc', 'zmdi-sort-asc',
        'zmdi-sort-desc', 'zmdi-spellcheck', 'zmdi-storage', 'zmdi-store-24', 'zmdi-store', 'zmdi-subway',
        'zmdi-sun', 'zmdi-tab-unselected', 'zmdi-tab', 'zmdi-tag-close', 'zmdi-tag-more', 'zmdi-tag',
        'zmdi-thumb-down', 'zmdi-thumb-up-down', 'zmdi-thumb-up', 'zmdi-ticket-star', 'zmdi-toll', 'zmdi-toys',
        'zmdi-traffic', 'zmdi-translate', 'zmdi-triangle-down', 'zmdi-triangle-up', 'zmdi-truck', 'zmdi-turning-sign',
        'zmdi-wallpaper', 'zmdi-washing-machine', 'zmdi-window-maximize', 'zmdi-window-minimize', 'zmdi-window-restore', 'zmdi-wrench',
        'zmdi-zoom-in', 'zmdi-zoom-out', 'zmdi-alert-circle-o', 'zmdi-alert-circle', 'zmdi-alert-octagon', 'zmdi-alert-polygon',
        'zmdi-alert-triangle', 'zmdi-help-outline', 'zmdi-help', 'zmdi-info-outline', 'zmdi-info', 'zmdi-notifications-active',
        'zmdi-notifications-add', 'zmdi-notifications-none', 'zmdi-notifications-off', 'zmdi-notifications-paused', 'zmdi-notifications', 'zmdi-account-add',
        'zmdi-account-box-mail', 'zmdi-account-box-o', 'zmdi-account-box-phone', 'zmdi-account-box', 'zmdi-account-calendar', 'zmdi-account-circle',
        'zmdi-account-o', 'zmdi-account', 'zmdi-accounts-add', 'zmdi-accounts-alt', 'zmdi-accounts-list-alt', 'zmdi-accounts-list',
        'zmdi-accounts-outline', 'zmdi-accounts', 'zmdi-face', 'zmdi-female', 'zmdi-male-alt', 'zmdi-male-female',
        'zmdi-male', 'zmdi-mood-bad', 'zmdi-mood', 'zmdi-run', 'zmdi-walk', 'zmdi-cloud-box',
        'zmdi-cloud-circle', 'zmdi-cloud-done', 'zmdi-cloud-download', 'zmdi-cloud-off', 'zmdi-cloud-outline-alt', 'zmdi-cloud-outline',
        'zmdi-cloud-upload', 'zmdi-cloud', 'zmdi-download', 'zmdi-file-plus', 'zmdi-file-text', 'zmdi-file',
        'zmdi-folder-outline', 'zmdi-folder-person', 'zmdi-folder-star-alt', 'zmdi-folder-star', 'zmdi-folder', 'zmdi-gif',
        'zmdi-upload', 'zmdi-border-all', 'zmdi-border-bottom', 'zmdi-border-clear', 'zmdi-border-color', 'zmdi-border-horizontal',
        'zmdi-border-inner', 'zmdi-border-left', 'zmdi-border-outer', 'zmdi-border-right', 'zmdi-border-style', 'zmdi-border-top',
        'zmdi-border-vertical', 'zmdi-copy', 'zmdi-crop', 'zmdi-format-align-center', 'zmdi-format-align-justify', 'zmdi-format-align-left',
        'zmdi-format-align-right', 'zmdi-format-bold', 'zmdi-format-clear-all', 'zmdi-format-clear', 'zmdi-format-color-fill', 'zmdi-format-color-reset',
        'zmdi-format-color-text', 'zmdi-format-indent-decrease', 'zmdi-format-indent-increase', 'zmdi-format-italic', 'zmdi-format-line-spacing', 'zmdi-format-list-bulleted',
        'zmdi-format-list-numbered', 'zmdi-format-ltr', 'zmdi-format-rtl', 'zmdi-format-size', 'zmdi-format-strikethrough-s', 'zmdi-format-strikethrough',
        'zmdi-format-subject', 'zmdi-format-underlined', 'zmdi-format-valign-bottom', 'zmdi-format-valign-center', 'zmdi-format-valign-top', 'zmdi-redo',
        'zmdi-select-all', 'zmdi-space-bar', 'zmdi-text-format', 'zmdi-transform', 'zmdi-undo', 'zmdi-wrap-text',
        'zmdi-comment-alert', 'zmdi-comment-alt-text', 'zmdi-comment-alt', 'zmdi-comment-edit', 'zmdi-comment-image', 'zmdi-comment-list',
        'zmdi-comment-more', 'zmdi-comment-outline', 'zmdi-comment-text-alt', 'zmdi-comment-text', 'zmdi-comment-video', 'zmdi-comment',
        'zmdi-comments', 'zmdi-check-all', 'zmdi-check-circle-u', 'zmdi-check-circle', 'zmdi-check-square', 'zmdi-check',
        'zmdi-circle-o', 'zmdi-circle', 'zmdi-dot-circle-alt', 'zmdi-dot-circle', 'zmdi-minus-circle-outline', 'zmdi-minus-circle',
        'zmdi-minus-square', 'zmdi-minus', 'zmdi-plus-circle-o-duplicate', 'zmdi-plus-circle-o', 'zmdi-plus-circle', 'zmdi-plus-square',
        'zmdi-plus', 'zmdi-square-o', 'zmdi-star-circle', 'zmdi-star-half', 'zmdi-star-outline', 'zmdi-star',
        'zmdi-bluetooth-connected', 'zmdi-bluetooth-off', 'zmdi-bluetooth-search', 'zmdi-bluetooth-setting', 'zmdi-bluetooth', 'zmdi-camera-add',
        'zmdi-camera-alt', 'zmdi-camera-bw', 'zmdi-camera-front', 'zmdi-camera-mic', 'zmdi-camera-party-mode', 'zmdi-camera-rear',
        'zmdi-camera-roll', 'zmdi-camera-switch', 'zmdi-camera', 'zmdi-card-alert', 'zmdi-card-off', 'zmdi-card-sd',
        'zmdi-card-sim', 'zmdi-desktop-mac', 'zmdi-desktop-windows', 'zmdi-device-hub', 'zmdi-devices-off', 'zmdi-devices',
        'zmdi-dock', 'zmdi-floppy', 'zmdi-gamepad', 'zmdi-gps-dot', 'zmdi-gps-off', 'zmdi-gps',
        'zmdi-headset-mic', 'zmdi-headset', 'zmdi-input-antenna', 'zmdi-input-composite', 'zmdi-input-hdmi', 'zmdi-input-power',
        'zmdi-input-svideo', 'zmdi-keyboard-hide', 'zmdi-keyboard', 'zmdi-laptop-chromebook', 'zmdi-laptop-mac', 'zmdi-laptop',
        'zmdi-mic-off', 'zmdi-mic-outline', 'zmdi-mic-setting', 'zmdi-mic', 'zmdi-mouse', 'zmdi-network-alert',
        'zmdi-network-locked', 'zmdi-network-off', 'zmdi-network-outline', 'zmdi-network-setting', 'zmdi-network', 'zmdi-phone-bluetooth',
        'zmdi-phone-end', 'zmdi-phone-forwarded', 'zmdi-phone-in-talk', 'zmdi-phone-locked', 'zmdi-phone-missed', 'zmdi-phone-msg',
        'zmdi-phone-paused', 'zmdi-phone-ring', 'zmdi-phone-setting', 'zmdi-phone-sip', 'zmdi-phone', 'zmdi-portable-wifi-changes',
        'zmdi-portable-wifi-off', 'zmdi-portable-wifi', 'zmdi-radio', 'zmdi-reader', 'zmdi-remote-control-alt', 'zmdi-remote-control',
        'zmdi-router', 'zmdi-scanner', 'zmdi-smartphone-android', 'zmdi-smartphone-download', 'zmdi-smartphone-erase', 'zmdi-smartphone-info',
        'zmdi-smartphone-iphone', 'zmdi-smartphone-landscape-lock', 'zmdi-smartphone-landscape', 'zmdi-smartphone-lock', 'zmdi-smartphone-portrait-lock', 'zmdi-smartphone-ring',
        'zmdi-smartphone-setting', 'zmdi-smartphone-setup', 'zmdi-smartphone', 'zmdi-speaker', 'zmdi-tablet-android:', 'zmdi-tablet-mac',
        'zmdi-tablet', 'zmdi-tv-alt-play', 'zmdi-tv-list', 'zmdi-tv-play', 'zmdi-tv', 'zmdi-usb',
        'zmdi-videocam-off', 'zmdi-videocam-switch', 'zmdi-videocam', 'zmdi-watch', 'zmdi-wifi-alt-2', 'zmdi-wifi-alt',
        'zmdi-wifi-info', 'zmdi-wifi-lock', 'zmdi-wifi-off', 'zmdi-wifi-outline', 'zmdi-wifi', 'zmdi-arrow-left-bottom',
        'zmdi-arrow-left', 'zmdi-arrow-merge', 'zmdi-arrow-missed', 'zmdi-arrow-right-top', 'zmdi-arrow-right', 'zmdi-arrow-split',
        'zmdi-arrows', 'zmdi-caret-down-circle', 'zmdi-caret-down', 'zmdi-caret-left-circle', 'zmdi-caret-left', 'zmdi-caret-right-circle',
        'zmdi-caret-right', 'zmdi-caret-up-circle', 'zmdi-caret-up', 'zmdi-chevron-down', 'zmdi-chevron-left', 'zmdi-chevron-right',
        'zmdi-chevron-up', 'zmdi-forward', 'zmdi-long-arrow-down', 'zmdi-long-arrow-left', 'zmdi-long-arrow-return', 'zmdi-long-arrow-right',
        'zmdi-long-arrow-tab', 'zmdi-long-arrow-up', 'zmdi-rotate-ccw', 'zmdi-rotate-cw', 'zmdi-rotate-left', 'zmdi-rotate-right',
        'zmdi-square-down', 'zmdi-square-right', 'zmdi-swap-alt', 'zmdi-swap-vertical-circle', 'zmdi-swap-vertical', 'zmdi-swap',
        'zmdi-trending-down', 'zmdi-trending-flat', 'zmdi-trending-up', 'zmdi-unfold-less', 'zmdi-unfold-more', 'zmdi-apps',
        'zmdi-grid-off', 'zmdi-grid', 'zmdi-view-agenda', 'zmdi-view-array', 'zmdi-view-carousel', 'zmdi-view-column',
        'zmdi-view-comfy', 'zmdi-view-compact', 'zmdi-view-dashboard', 'zmdi-view-day', 'zmdi-view-headline', 'zmdi-view-list-alt',
        'zmdi-view-list', 'zmdi-view-module', 'zmdi-view-quilt', 'zmdi-view-stream', 'zmdi-view-subtitles', 'zmdi-view-toc',
        'zmdi-view-web', 'zmdi-view-week', 'zmdi-widgets', 'zmdi-alarm-check', 'zmdi-alarm-off', 'zmdi-alarm-plus',
        'zmdi-alarm-snooze', 'zmdi-alarm', 'zmdi-calendar-alt', 'zmdi-calendar-check', 'zmdi-calendar-close', 'zmdi-calendar-note',
        'zmdi-calendar', 'zmdi-time-countdown', 'zmdi-time-interval', 'zmdi-time-restore-setting', 'zmdi-time-restore', 'zmdi-time',
        'zmdi-timer-off', 'zmdi-timer', 'zmdi-android-alt', 'zmdi-android', 'zmdi-apple', 'zmdi-behance',
        'zmdi-codepen', 'zmdi-dribbble', 'zmdi-dropbox', 'zmdi-evernote', 'zmdi-facebook-box', 'zmdi-facebook',
        'zmdi-github-box', 'zmdi-github', 'zmdi-google-drive', 'zmdi-google-earth', 'zmdi-google-glass', 'zmdi-google-maps',
        'zmdi-google-pages', 'zmdi-google-play', 'zmdi-google-plus-box', 'zmdi-google-plus', 'zmdi-google', 'zmdi-instagram',
        'zmdi-language-css3', 'zmdi-language-html5', 'zmdi-language-javascript', 'zmdi-language-python-alt', 'zmdi-language-python', 'zmdi-lastfm',
        'zmdi-linkedin-box', 'zmdi-paypal', 'zmdi-pinterest-box', 'zmdi-pocket', 'zmdi-polymer', 'zmdi-share',
        'zmdi-stack-overflow', 'zmdi-steam-square', 'zmdi-steam', 'zmdi-twitter-box', 'zmdi-twitter', 'zmdi-vk',
        'zmdi-wikipedia', 'zmdi-windows', 'zmdi-aspect-ratio-alt', 'zmdi-aspect-ratio', 'zmdi-blur-circular', 'zmdi-blur-linear',
        'zmdi-blur-off', 'zmdi-blur', 'zmdi-brightness-2', 'zmdi-brightness-3', 'zmdi-brightness-4', 'zmdi-brightness-5',
        'zmdi-brightness-6', 'zmdi-brightness-7', 'zmdi-brightness-auto', 'zmdi-brightness-setting', 'zmdi-broken-image', 'zmdi-center-focus-strong',
        'zmdi-center-focus-weak', 'zmdi-compare', 'zmdi-crop-16-9', 'zmdi-crop-3-2', 'zmdi-crop-5-4', 'zmdi-crop-7-5',
        'zmdi-crop-din', 'zmdi-crop-free', 'zmdi-crop-landscape', 'zmdi-crop-portrait', 'zmdi-crop-square', 'zmdi-exposure-alt',
        'zmdi-exposure', 'zmdi-filter-b-and-w', 'zmdi-filter-center-focus', 'zmdi-filter-frames', 'zmdi-filter-tilt-shift', 'zmdi-gradient',
        'zmdi-grain', 'zmdi-graphic-eq', 'zmdi-hdr-off', 'zmdi-hdr-strong', 'zmdi-hdr-weak', 'zmdi-hdr',
        'zmdi-iridescent', 'zmdi-leak-off', 'zmdi-leak', 'zmdi-looks', 'zmdi-loupe', 'zmdi-panorama-horizontal',
        'zmdi-panorama-vertical', 'zmdi-panorama-wide-angle', 'zmdi-photo-size-select-large', 'zmdi-photo-size-select-small', 'zmdi-picture-in-picture', 'zmdi-slideshow',
        'zmdi-texture', 'zmdi-tonality', 'zmdi-vignette', 'zmdi-wb-auto', 'zmdi-eject-alt', 'zmdi-eject',
        'zmdi-equalizer', 'zmdi-fast-forward', 'zmdi-fast-rewind', 'zmdi-forward-10', 'zmdi-forward-30', 'zmdi-forward-5',
        'zmdi-hearing', 'zmdi-pause-circle-outline', 'zmdi-pause-circle', 'zmdi-pause', 'zmdi-play-circle-outline', 'zmdi-play-circle',
        'zmdi-play', 'zmdi-playlist-audio', 'zmdi-playlist-plus', 'zmdi-repeat-one', 'zmdi-repeat', 'zmdi-replay-10',
        'zmdi-replay-30', 'zmdi-replay-5', 'zmdi-replay', 'zmdi-shuffle', 'zmdi-skip-next', 'zmdi-skip-previous',
        'zmdi-stop', 'zmdi-surround-sound', 'zmdi-tune', 'zmdi-volume-down', 'zmdi-volume-mute', 'zmdi-volume-off',
        'zmdi-volume-up', 'zmdi-n-1-square', 'zmdi-n-2-square', 'zmdi-n-3-square', 'zmdi-n-4-square', 'zmdi-n-5-square',
        'zmdi-n-6-square', 'zmdi-neg-1', 'zmdi-neg-2', 'zmdi-plus-1', 'zmdi-plus-2', 'zmdi-sec-10',
        'zmdi-sec-3', 'zmdi-zero', 'zmdi-airline-seat-flat-angled', 'zmdi-airline-seat-flat', 'zmdi-airline-seat-individual-suite', 'zmdi-airline-seat-legroom-extra',
        'zmdi-airline-seat-legroom-normal', 'zmdi-airline-seat-legroom-reduced', 'zmdi-airline-seat-recline-extra', 'zmdi-airline-seat-recline-normal', 'zmdi-airplay', 'zmdi-closed-caption',
        'zmdi-confirmation-number', 'zmdi-developer-board', 'zmdi-disc-full', 'zmdi-explicit', 'zmdi-flight-land', 'zmdi-flight-takeoff',
        'zmdi-flip-to-back', 'zmdi-flip-to-front', 'zmdi-group-work', 'zmdi-hd', 'zmdi-hq', 'zmdi-markunread-mailbox',
        'zmdi-memory', 'zmdi-nfc', 'zmdi-play-for-work', 'zmdi-power-input', 'zmdi-present-to-all', 'zmdi-satellite',
        'zmdi-tap-and-play', 'zmdi-vibration', 'zmdi-voicemail', 'zmdi-3d-rotation', 'zmdi-airplane-off', 'zmdi-airplane',
        'zmdi-album', 'zmdi-archive', 'zmdi-assignment-account', 'zmdi-assignment-alert', 'zmdi-assignment-check', 'zmdi-assignment-o',
        'zmdi-assignment-return', 'zmdi-assignment-returned', 'zmdi-assignment', 'zmdi-attachment-alt', 'zmdi-attachment', 'zmdi-audio',
        'zmdi-badge-check', 'zmdi-balance-wallet', 'zmdi-balance', 'zmdi-battery-alert', 'zmdi-battery-flash', 'zmdi-battery-unknown',
        'zmdi-battery', 'zmdi-bike', 'zmdi-block-alt', 'zmdi-block', 'zmdi-boat', 'zmdi-book-image',
        'zmdi-book', 'zmdi-bookmark-outline', 'zmdi-bookmark', 'zmdi-brush', 'zmdi-bug', 'zmdi-bus',
        'zmdi-cake', 'zmdi-car-taxi', 'zmdi-car-wash', 'zmdi-car', 'zmdi-card-giftcard', 'zmdi-card-membership',
        'zmdi-card-travel', 'zmdi-card', 'zmdi-case-check', 'zmdi-case-download', 'zmdi-case-play', 'zmdi-case',
        'zmdi-cast-connected', 'zmdi-cast', 'zmdi-chart-donut', 'zmdi-chart', 'zmdi-city-alt', 'zmdi-city',
        'zmdi-close-circle-o', 'zmdi-close-circle', 'zmdi-close', 'zmdi-cocktail', 'zmdi-code-setting', 'zmdi-code-smartphone',
        'zmdi-code-smartphone', 'zmdi-code', 'zmdi-coffee', 'zmdi-collection-bookmark', 'zmdi-collection-case-play', 'zmdi-collection-folder-image',
        'zmdi-collection-image-o', 'zmdi-collection-image', 'zmdi-collection-item-1', 'zmdi-collection-item-2', 'zmdi-collection-item-3', 'zmdi-collection-item-4',
        'zmdi-collection-item-5', 'zmdi-collection-item-6', 'zmdi-collection-item-7', 'zmdi-collection-item-8', 'zmdi-collection-item-9-plus', 'zmdi-collection-item-9',
        'zmdi-collection-item', 'zmdi-collection-music', 'zmdi-collection-pdf', 'zmdi-collection-plus', 'zmdi-collection-speaker', 'zmdi-collection-tex',
        'zmdi-collection-video', 'zmdi-compass', 'zmdi-cutlery', 'zmdi-delete', 'zmdi-dialpad', 'zmdi-dns',
        'zmdi-drink', 'zmdi-edit', 'zmdi-email-open', 'zmdi-email', 'zmdi-eye-off', 'zmdi-eye',
        'zmdi-eyedropper', 'zmdi-favorite-outline', 'zmdi-favorite', 'zmdi-filter-list', 'zmdi-fire', 'zmdi-flag',
        'zmdi-flare', 'zmdi-flash-auto', 'zmdi-flash-off', 'zmdi-flash', 'zmdi-flip', 'zmdi-flower-alt',
        'zmdi-flower', 'zmdi-font', 'zmdi-fullscreen-alt', 'zmdi-fullscreen-exit', 'zmdi-fullscreen', 'zmdi-functions',
        'zmdi-gas-station', 'zmdi-gesture', 'zmdi-globe-alt', 'zmdi-globe-lock', 'zmdi-globe', 'zmdi-graduation-cap',
        'zmdi-home', 'zmdi-hospital-alt', 'zmdi-hospital', 'zmdi-hotel', 'zmdi-hourglass-alt', 'zmdi-hourglass-outline',
        'zmdi-hourglass', 'zmdi-http', 'zmdi-image-alt', 'zmdi-image-o', 'zmdi-image', 'zmdi-inbox',
        'zmdi-invert-colors-off', 'zmdi-invert-colors', 'zmdi-key', 'zmdi-label-alt-outline', 'zmdi-label-alt', 'zmdi-label-heart',
        'zmdi-label', 'zmdi-labels', 'zmdi-lamp', 'zmdi-landscape', 'zmdi-layers-off', 'zmdi-layers',
        'zmdi-library', 'zmdi-link', 'zmdi-lock-open', 'zmdi-lock-outline', 'zmdi-lock', 'zmdi-mail-reply-all',
        'zmdi-mail-reply', 'zmdi-mail-send', 'zmdi-mall', 'zmdi-map', 'zmdi-menu', 'zmdi-money-box',
        'zmdi-money-off', 'zmdi-money', 'zmdi-more-vert', 'zmdi-more', 'zmdi-movie-alt', 'zmdi-movie',
        'zmdi-nature-people', 'zmdi-nature', 'zmdi-navigation', 'zmdi-open-in-browser', 'mdi-open-in-new', 'zmdi-palette',
        'zmdi-parking', 'zmdi-pin-account', 'zmdi-pin-assistant', 'zmdi-pin-drop', 'zmdi-pin-help', 'zmdi-pin-off',
        'zmdi-pin', 'zmdi-pizza', 'zmdi-plaster', 'zmdi-power-setting', 'zmdi-power', 'zmdi-print',
        'zmdi-puzzle-piece', 'zmdi-quote', 'zmdi-railway', 'zmdi-receipt', 'zmdi-refresh-alt', 'zmdi-refresh-sync-alert',
        'zmdi-refresh-sync-off', 'zmdi-refresh-sync', 'zmdi-refresh', 'zmdi-roller', 'zmdi-ruler', 'zmdi-scissors',
        'zmdi-screen-rotation-lock', 'zmdi-screen-rotation', 'zmdi-search-for', 'zmdi-search-in-file', 'zmdi-search-in-page', 'zmdi-search-replace',
        'zmdi-search', 'zmdi-seat', 'zmdi-settings-square', 'zmdi-settings', 'zmdi-shield-check', 'zmdi-shield-security',
        'zmdi-shopping-basket', 'zmdi-shopping-cart-plus', 'zmdi-shopping-cart', 'zmdi-sign-in', 'zmdi-sort-amount-asc', 'zmdi-sort-amount-desc',
        'zmdi-sort-asc', 'zmdi-sort-desc', 'zmdi-spellcheck', 'zmdi-storage', 'zmdi-store-24', 'zmdi-store',
        'zmdi-subway', 'zmdi-sun', 'zmdi-tab-unselected', 'zmdi-tab', 'zmdi-tag-close', 'zmdi-tag-more',
        'zmdi-tag', 'zmdi-thumb-down', 'zmdi-thumb-up-down', 'zmdi-thumb-up', 'zmdi-ticket-star', 'zmdi-toll',
        'zmdi-toys', 'zmdi-traffic', 'zmdi-translate', 'zmdi-triangle-down', 'zmdi-triangle-up', 'zmdi-truck',
        'zmdi-turning-sign', 'zmdi-wallpaper', 'zmdi-washing-machine', 'zmdi-window-maximize', 'zmdi-window-minimize', 'zmdi-window-restore',
        'zmdi-wrench', 'zmdi-zoom-in', 'zmdi-zoom-out', 'zmdi-alert-circle-o', 'zmdi-alert-circle', 'zmdi-alert-octagon',
        'zmdi-alert-polygon', 'zmdi-alert-triangle', 'zmdi-help-outline', 'zmdi-help', 'zmdi-info-outline', 'zmdi-info',
        'zmdi-notifications-active', 'zmdi-notifications-add', 'zmdi-notifications-none', 'zmdi-notifications-off', 'zmdi-notifications-paused', 'zmdi-notifications',
        'zmdi-account-add', 'zmdi-account-box-mail', 'zmdi-account-box-o', 'zmdi-account-box-phone', 'zmdi-account-box', 'zmdi-account-calendar',
        'zmdi-account-circle', 'zmdi-account-o', 'zmdi-account', 'zmdi-accounts-add', 'zmdi-accounts-alt', 'zmdi-accounts-list-alt',
        'zmdi-accounts-list', 'zmdi-accounts-outline', 'zmdi-accounts', 'zmdi-face', 'zmdi-female', 'zmdi-male-alt',
        'zmdi-male-female', 'zmdi-male', 'zmdi-mood-bad', 'zmdi-mood', 'zmdi-run', 'zmdi-walk',
        'zmdi-cloud-box', 'zmdi-cloud-circle', 'zmdi-cloud-done', 'zmdi-cloud-download', 'zmdi-cloud-off', 'zmdi-cloud-outline-alt',
        'zmdi-cloud-outline', 'zmdi-cloud-upload', 'zmdi-cloud', 'zmdi-download', 'zmdi-file-plus', 'zmdi-file-text',
        'zmdi-file', 'zmdi-folder-outline', 'zmdi-folder-person', 'zmdi-folder-star-alt', 'zmdi-folder-star', 'zmdi-folder',
        'zmdi-gif', 'zmdi-upload', 'zmdi-border-all', 'zmdi-border-bottom', 'zmdi-border-clear', 'zmdi-border-color',
        'zmdi-border-horizontal', 'zmdi-border-inner', 'zmdi-border-left', 'zmdi-border-outer', 'zmdi-border-right', 'zmdi-border-style',
        'zmdi-border-top', 'zmdi-border-vertical', 'zmdi-copy', 'zmdi-crop', 'zmdi-format-align-center', 'zmdi-format-align-justify',
        'zmdi-format-align-left', 'zmdi-format-align-right', 'zmdi-format-bold', 'zmdi-format-clear-all', 'zmdi-format-clear', 'zmdi-format-color-fill',
        'zmdi-format-color-reset', 'zmdi-format-color-text', 'zmdi-format-indent-decrease', 'zmdi-format-indent-increase', 'zmdi-format-italic', 'zmdi-format-line-spacing',
        'zmdi-format-list-bulleted', 'zmdi-format-list-numbered', 'zmdi-format-ltr', 'zmdi-format-rtl', 'zmdi-format-size', 'zmdi-format-strikethrough-s',
        'zmdi-format-strikethrough', 'zmdi-format-subject', 'zmdi-format-underlined', 'zmdi-format-valign-bottom', 'zmdi-format-valign-center', 'zmdi-format-valign-top',
        'zmdi-redo', 'zmdi-select-all', 'zmdi-space-bar', 'zmdi-text-format', 'zmdi-transform', 'zmdi-undo',
        'zmdi-wrap-text', 'zmdi-comment-alert', 'zmdi-comment-alt-text', 'zmdi-comment-alt', 'zmdi-comment-edit', 'zmdi-comment-image',
        'zmdi-comment-list', 'zmdi-comment-more', 'zmdi-comment-outline', 'zmdi-comment-text-alt', 'zmdi-comment-text', 'zmdi-comment-video',
        'zmdi-comment', 'zmdi-comments', 'zmdi-check-all', 'zmdi-check-circle-u', 'zmdi-check-circle', 'zmdi-check-square',
        'zmdi-check', 'zmdi-circle-o', 'zmdi-circle', 'zmdi-dot-circle-alt', 'zmdi-dot-circle', 'zmdi-minus-circle-outline',
        'zmdi-minus-circle', 'zmdi-minus-square', 'zmdi-minus', 'zmdi-plus-circle-o-duplicate', 'zmdi-plus-circle-o', 'zmdi-plus-circle',
        'zmdi-plus-square', 'zmdi-plus', 'zmdi-square-o', 'zmdi-star-circle', 'zmdi-star-half', 'zmdi-star-outline',
        'zmdi-star', 'zmdi-bluetooth-connected', 'zmdi-bluetooth-off', 'zmdi-bluetooth-search', 'zmdi-bluetooth-setting', 'zmdi-bluetooth',
        'zmdi-camera-add', 'zmdi-camera-alt', 'zmdi-camera-bw', 'zmdi-camera-front', 'zmdi-camera-mic', 'zmdi-camera-party-mode',
        'zmdi-camera-rear', 'zmdi-camera-roll', 'zmdi-camera-switch', 'zmdi-camera', 'zmdi-card-alert', 'zmdi-card-off',
        'zmdi-card-sd', 'zmdi-card-sim', 'zmdi-desktop-mac', 'zmdi-desktop-windows', 'zmdi-device-hub', 'zmdi-devices-off',
        'zmdi-devices', 'zmdi-dock', 'zmdi-floppy', 'zmdi-gamepad', 'zmdi-gps-dot', 'zmdi-gps-off',
        'zmdi-gps', 'zmdi-headset-mic', 'zmdi-headset', 'zmdi-input-antenna', 'zmdi-input-composite', 'zmdi-input-hdmi',
        'zmdi-input-power', 'zmdi-input-svideo', 'zmdi-keyboard-hide', 'zmdi-keyboard', 'zmdi-laptop-chromebook', 'zmdi-laptop-mac',
        'zmdi-laptop', 'zmdi-mic-off', 'zmdi-mic-outline', 'zmdi-mic-setting', 'zmdi-mic', 'zmdi-mouse',
        'zmdi-network-alert', 'zmdi-network-locked', 'zmdi-network-off', 'zmdi-network-outline', 'zmdi-network-setting', 'zmdi-network',
        'zmdi-phone-bluetooth', 'zmdi-phone-end', 'zmdi-phone-forwarded', 'zmdi-phone-in-talk', 'zmdi-phone-locked', 'zmdi-phone-missed',
        'zmdi-phone-msg', 'zmdi-phone-paused', 'zmdi-phone-ring', 'zmdi-phone-setting', 'zmdi-phone-sip', 'zmdi-phone',
        'zmdi-portable-wifi-changes', 'zmdi-portable-wifi-off', 'zmdi-portable-wifi', 'zmdi-radio', 'zmdi-reader', 'zmdi-remote-control-alt',
        'zmdi-remote-control', 'zmdi-router', 'zmdi-scanner', 'zmdi-smartphone-android', 'zmdi-smartphone-download', 'zmdi-smartphone-erase',
        'zmdi-smartphone-info', 'zmdi-smartphone-iphone', 'zmdi-smartphone-landscape-lock', 'zmdi-smartphone-landscape', 'zmdi-smartphone-lock', 'zmdi-smartphone-portrait-lock',
        'zmdi-smartphone-ring', 'zmdi-smartphone-setting', 'zmdi-smartphone-setup', 'zmdi-smartphone', 'zmdi-speaker', 'zmdi-tablet-android',
        'zmdi-tablet-mac', 'zmdi-tablet', 'zmdi-tv-alt-play', 'zmdi-tv-list', 'zmdi-tv-play', 'zmdi-tv',
        'zmdi-usb', 'zmdi-videocam-off', 'zmdi-videocam-switch', 'zmdi-videocam', 'zmdi-watch', 'zmdi-wifi-alt-2',
        'zmdi-wifi-alt', 'zmdi-wifi-info', 'zmdi-wifi-lock', 'zmdi-wifi-off', 'zmdi-wifi-outline', 'zmdi-wifi',
        'zmdi-arrow-left-bottom', 'zmdi-arrow-left', 'zmdi-arrow-merge', 'zmdi-arrow-missed', 'zmdi-arrow-right-top', 'zmdi-arrow-right',
        'zmdi-arrow-split', 'zmdi-arrows', 'zmdi-caret-down-circle', 'zmdi-caret-down', 'zmdi-caret-left-circle', 'zmdi-caret-left',
        'zmdi-caret-right-circle', 'zmdi-caret-right', 'zmdi-caret-up-circle', 'zmdi-caret-up', 'zmdi-chevron-down', 'zmdi-chevron-left',
        'zmdi-chevron-right', 'zmdi-chevron-up', 'zmdi-forward', 'zmdi-long-arrow-down', 'zmdi-long-arrow-left', 'zmdi-long-arrow-return',
        'zmdi-long-arrow-right', 'zmdi-long-arrow-tab', 'zmdi-long-arrow-up', 'zmdi-rotate-ccw', 'zmdi-rotate-cw', 'zmdi-rotate-left',
        'zmdi-rotate-right', 'zmdi-square-down', 'zmdi-square-right', 'zmdi-swap-alt', 'zmdi-swap-vertical-circle', 'zmdi-swap-vertical',
        'zmdi-swap', 'zmdi-trending-down', 'zmdi-trending-flat', 'zmdi-trending-up', 'zmdi-unfold-less', 'zmdi-unfold-more',
        'zmdi-apps', 'zmdi-grid-off', 'zmdi-grid', 'zmdi-view-agenda', 'zmdi-view-array', 'zmdi-view-carousel',
        'zmdi-view-column', 'zmdi-view-comfy', 'zmdi-view-compact', 'zmdi-view-dashboard', 'zmdi-view-day', 'zmdi-view-headline',
        'zmdi-view-list-alt', 'zmdi-view-list', 'zmdi-view-module', 'zmdi-view-quilt', 'zmdi-view-stream', 'zmdi-view-subtitles',
        'zmdi-view-toc', 'zmdi-view-web', 'zmdi-view-week', 'zmdi-widgets', 'zmdi-alarm-check', 'zmdi-alarm-off',
        'zmdi-alarm-plus', 'zmdi-alarm-snooze', 'zmdi-alarm', 'zmdi-calendar-alt', 'zmdi-calendar-check', 'zmdi-calendar-close',
        'zmdi-calendar-note', 'zmdi-calendar', 'zmdi-time-countdown', 'zmdi-time-interval', 'zmdi-time-restore-setting', 'zmdi-time-restore',
        'zmdi-time', 'zmdi-timer-off', 'zmdi-timer', 'zmdi-android-alt', 'zmdi-android', 'zmdi-apple',
        'zmdi-behance', 'zmdi-codepen', 'zmdi-dribbble', 'zmdi-dropbox', 'zmdi-evernote', 'zmdi-facebook-box',
        'zmdi-facebook', 'zmdi-github-box', 'zmdi-github', 'zmdi-google-drive', 'zmdi-google-earth', 'zmdi-google-glass',
        'zmdi-google-maps', 'zmdi-google-pages', 'zmdi-google-play', 'zmdi-google-plus-box', 'zmdi-google-plus', 'zmdi-google',
        'zmdi-instagram', 'zmdi-language-css3', 'zmdi-language-html5', 'zmdi-language-javascript', 'zmdi-language-python-alt', 'zmdi-language-python',
        'zmdi-lastfm', 'zmdi-linkedin-box', 'zmdi-paypal', 'zmdi-pinterest-box', 'zmdi-pocket', 'zmdi-polymer',
        'zmdi-share', 'zmdi-stack-overflow', 'zmdi-steam-square', 'zmdi-steam', 'zmdi-twitter-box', 'zmdi-twitter',
        'zmdi-vk', 'zmdi-wikipedia', 'zmdi-windows', 'zmdi-aspect-ratio-alt', 'zmdi-aspect-ratio', 'zmdi-blur-circular',
        'zmdi-blur-linear', 'zmdi-blur-off', 'zmdi-blur', 'zmdi-brightness-2', 'zmdi-brightness-3', 'zmdi-brightness-4',
        'zmdi-brightness-5', 'zmdi-brightness-6', 'zmdi-brightness-7', 'zmdi-brightness-auto', 'zmdi-brightness-setting', 'zmdi-broken-image',
        'zmdi-center-focus-strong', 'zmdi-center-focus-weak', 'zmdi-compare', 'zmdi-crop-16-9', 'zmdi-crop-3-2', 'zmdi-crop-5-4',
        'zmdi-crop-7-5', 'zmdi-crop-din', 'zmdi-crop-free', 'zmdi-crop-landscape', 'zmdi-crop-portrait', 'zmdi-crop-square',
        'zmdi-exposure-alt', 'zmdi-exposure', 'zmdi-filter-b-and-w', 'zmdi-filter-center-focus', 'zmdi-filter-frames', 'zmdi-filter-tilt-shift',
        'zmdi-gradient', 'zmdi-grain', 'zmdi-graphic-eq', 'zmdi-hdr-off', 'zmdi-hdr-strong', 'zmdi-hdr-weak',
        'zmdi-hdr', 'zmdi-iridescent', 'zmdi-leak-off', 'zmdi-leak', 'zmdi-looks', 'zmdi-loupe',
        'zmdi-panorama-horizontal', 'zmdi-panorama-vertical', 'zmdi-panorama-wide-angle', 'zmdi-photo-size-select-large', 'zmdi-photo-size-select-small', 'zmdi-picture-in-picture',
        'zmdi-slideshow', 'zmdi-texture', 'zmdi-tonality', 'zmdi-vignette', 'zmdi-wb-auto', 'zmdi-eject-alt',
        'zmdi-eject', 'zmdi-equalizer', 'zmdi-fast-forward', 'zmdi-fast-rewind', 'zmdi-forward-10', 'zmdi-forward-30',
        'zmdi-forward-5', 'zmdi-hearing', 'zmdi-pause-circle-outline', 'zmdi-pause-circle', 'zmdi-pause', 'zmdi-play-circle-outline',
        'zmdi-play-circle', 'zmdi-play', 'zmdi-playlist-audio', 'zmdi-playlist-plus', 'zmdi-repeat-one', 'zmdi-repeat',
        'zmdi-replay-10', 'zmdi-replay-30', 'zmdi-replay-5', 'zmdi-replay', 'zmdi-shuffle', 'zmdi-skip-next',
        'zmdi-skip-previous', 'zmdi-stop', 'zmdi-surround-sound', 'zmdi-tune', 'zmdi-volume-down', 'zmdi-volume-mute',
        'zmdi-volume-off', 'zmdi-volume-up', 'zmdi-n-1-square', 'zmdi-n-2-square', 'zmdi-n-3-square', 'zmdi-n-4-square',
        'zmdi-n-5-square', 'zmdi-n-6-square', 'zmdi-neg-1', 'zmdi-neg-2', 'zmdi-plus-1', 'zmdi-plus-2',
        'zmdi-sec-10', 'zmdi-sec-3', 'zmdi-zero', 'zmdi-airline-seat-flat-angled', 'zmdi-airline-seat-flat', 'zmdi-airline-seat-individual-suite',
        'zmdi-airline-seat-legroom-extra', 'zmdi-airline-seat-legroom-normal', 'zmdi-airline-seat-legroom-reduced', 'zmdi-airline-seat-recline-extra', 'zmdi-airline-seat-recline-normal', 'zmdi-airplay',
        'zmdi-closed-caption', 'zmdi-confirmation-number', 'zmdi-developer-board', 'zmdi-disc-full', 'zmdi-explicit', 'zmdi-flight-land',
        'zmdi-flight-takeoff', 'zmdi-flip-to-back', 'zmdi-flip-to-front', 'zmdi-group-work', 'zmdi-hd', 'zmdi-hq',
        'zmdi-markunread-mailbox', 'zmdi-memory', 'zmdi-nfc', 'zmdi-play-for-work', 'zmdi-power-input', 'zmdi-present-to-all',
        'zmdi-satellite', 'zmdi-tap-and-play', 'zmdi-vibration', 'zmdi-voicemail', 'zmdi-import-export', 'zmdi-swap-vertical-',
        'zmdi-airplanemode-inactive', 'zmdi-airplanemode-active', 'zmdi-rate-review', 'zmdi-comment-sign', 'zmdi-network-warning', 'zmdi-shopping-cart-add',
        'zmdi-file-add', 'zmdi-network-wifi-scan', 'zmdi-collection-add', 'zmdi-format-playlist-add', 'zmdi-format-queue-music', 'zmdi-plus-box',
        'zmdi-tag-backspace', 'zmdi-alarm-add', 'zmdi-battery-charging', 'zmdi-daydream-setting', 'zmdi-more-horiz', 'zmdi-book-photo',
        'zmdi-incandescent', 'zmdi-wb-iridescent', 'zmdi-calendar-remove', 'zmdi-refresh-sync-disabled', 'zmdi-refresh-sync-problem', 'zmdi-crop-original',
        'zmdi-power-off', 'zmdi-power-off-setting', 'zmdi-leak-remove', 'zmdi-star-border', 'zmdi-brightness-low', 'zmdi-brightness-medium',
        'zmdi-brightness-high', 'zmdi-smartphone-portrait', 'zmdi-live-tv', 'zmdi-format-textdirection-l-to-r', 'zmdi-format-textdirection-r-to-l', 'zmdi-arrow-back',
        'zmdi-arrow-forward', 'zmdi-arrow-in', 'zmdi-arrow-out', 'zmdi-rotate-90-degrees-ccw', 'zmdi-adb', 'zmdi-network-wifi',
        'zmdi-network-wifi-alt', 'zmdi-network-wifi-lock', 'zmdi-network-wifi-off', 'zmdi-network-wifi-outline', 'zmdi-network-wifi-info', 'zmdi-layers-clear',
        'zmdi-colorize', 'zmdi-format-paint', 'zmdi-format-quote', 'zmdi-camera-monochrome-photos', 'zmdi-sort-by-alpha', 'zmdi-folder-shared',
        'zmdi-folder-special', 'zmdi-comment-dots', 'zmdi-reorder', 'zmdi-dehaze', 'zmdi-sort', 'zmdi-pages',
        'zmdi-calendar-account', 'zmdi-paste', 'zmdi-cut', 'zmdi-save', 'zmdi-smartphone-code', 'zmdi-directions-bike',
        'zmdi-directions-boat', 'zmdi-directions-bus', 'zmdi-directions-car', 'zmdi-directions-railway', 'zmdi-directions-run', 'zmdi-directions-subway',
        'zmdi-directions-walk', 'zmdi-local-hotel', 'zmdi-local-activity', 'zmdi-local-play', 'zmdi-local-airport', 'zmdi-local-atm',
        'zmdi-local-bar', 'zmdi-local-cafe', 'zmdi-local-car-wash', 'zmdi-local-convenience-store', 'zmdi-local-dining', 'zmdi-local-drink',
        'zmdi-local-florist', 'zmdi-local-gas-station', 'zmdi-local-grocery-store', 'zmdi-local-hospital', 'zmdi-local-laundry-service', 'zmdi-local-library',
        'zmdi-local-mall', 'zmdi-local-movies', 'zmdi-local-offer', 'zmdi-local-parking', 'zmdi-local-parking', 'zmdi-local-pharmacy',
        'zmdi-local-phone', 'zmdi-local-pizza', 'zmdi-local-post-office', 'zmdi-local-printshop', 'zmdi-local-see', 'zmdi-local-shipping',
        'zmdi-local-store', 'zmdi-local-taxi', 'zmdi-local-wc', 'zmdi-my-location', 'zmdi-directions' 
    );
    $metaral_unique = array_unique($metarial);
    
    
    $lineIcon = array(
        'line-adjustments', 'line-alarmclock'. 'line-anchor', 'line-aperture', 'line-attachments', 'line-bargraph',
        'line-basket', 'line-beaker', 'line-bike', 'line-book-open', 'line-briefcase', 'line-browser',
        'line-calendar', 'line-camera', 'line-caution', 'line-chat', 'line-circle-compass', 'line-clipboard',
        'line-clock', 'line-cloud', 'line-compass', 'line-desktop', 'line-dial', 'line-document',
        'line-documents', 'line-download', 'line-dribbble', 'line-edit', 'line-envelope', 'line-expand',
        'line-facebook', 'line-flag', 'line-focus', 'line-gears', 'line-genius', 'line-gift',
        'line-global', 'line-globe', 'line-googleplus', 'line-grid', 'line-happy', 'line-hazardous',
        'line-heart', 'line-hotairballoon', 'line-hourglass', 'line-key', 'line-laptop', 'line-layers',
        'line-lifesaver', 'line-lightbulb', 'line-linegraph', 'line-linkedin', 'line-lock', 'line-magnifying-glass',
        'line-map', 'line-map-pin', 'line-megaphone', 'line-mic', 'line-mobile', 'line-newspaper',
        'line-notebook', 'line-paintbrush', 'line-paperclip', 'line-pencil', 'line-phone', 'line-picture',
        'line-pictures', 'line-piechart', 'line-presentation', 'line-pricetags', 'line-printer', 'line-profile-female',
        'line-profile-male', 'line-puzzle', 'line-quote', 'line-recycle', 'line-refresh', 'line-ribbon',
        'line-rss', 'line-sad', 'line-scissors', 'line-scope', 'line-search', 'line-shield',
        'line-speedometer', 'line-strategy', 'line-streetsign', 'line-tablet', 'line-telescope', 'line-toolbox',
        'line-tools', 'line-tools-2', 'line-traget', 'line-trophy', 'line-tumblr', 'line-twitter',
        'line-upload', 'line-video', 'line-wallet', 'line-wine'
    );
        
    $iconas = array();
    foreach($esen_77 as $esen_icon){
        $iconas[str_replace('.', '', $esen_icon)]=array('group' => 'essential');
    }
    foreach ($elIconsa as $icon)
    {
        $iconas[str_replace('.', '', $icon)] = array('group' => 'elegant');
    }
    foreach ($simpleIcona as $icons)
    {
        $iconas[str_replace('.', '', $icons)] = array('group' => 'lineicon');
    }
    foreach ($font_awesome_icons as $class => $con)
    {
        $iconas['fa '.$class] = array('group' => 'fontawesome');
    }
    foreach ($fie_field as $class)
    {
        $iconas[$class] = array('group' => 'pie_icon_field');
    }
    foreach ($pie_strok as $class)
    {
        $iconas[$class] = array('group' => 'pie_icon_stroke');
    }
    foreach ($strock as $class)
    {
        $iconas[$class] = array('group' => 'stroke_gap_icon');
    }
    foreach ($metaral_unique as $class)
    {
        $iconas[$class] = array('group' => 'metarial_icon');
    }
    foreach ($lineIcon as $class)
    {
        $iconas[$class] = array('group' => 'line_icon');
    }
    $sets['tw_line_icon_set'] = array(
        'font-style-src' => get_template_directory_uri().'/framework-customizations/Assets/css/icon.css',
        'container-class' => 'fa-lg', // some fonts need special wrapper class to display properly
        'groups' => array(
            'elegant' => esc_html__('Elegant Icons', 'martin'),
            'lineicon' => esc_html__('Simple Line Icons', 'martin'),
            'fontawesome' => esc_html__('Fontawesome Icons', 'martin'),
            'pie_icon_field' => esc_html__('Pie Icon Filled', 'martin'),
            'pie_icon_stroke' => esc_html__('Pie Icon Stroke', 'martin'),
            'essential'=>esc_html__('77 Essential Icons','martin'),
            'stroke_gap_icon'=>esc_html__('Stroke Gap Icon','martin'),
            'metarial_icon'=> esc_html__('Metarial Icons', 'martin'),
            'line_icon'=> esc_html__('Line Icons', 'martin'),
        ),
        'icons' => $iconas
    );

    return $sets;
}
add_filter('fw_option_type_icon_sets', 'martin_filter_theme_new_icon_set');