<?php


class MediaWidget extends WP_Widget
{
    public $widget_ID;

    public $widget_name;

    public $widget_options = array();

    public $control_options = array();

    public function __construct()
    {
        $this->widget_ID = "webalive_media_widget";

        $this->widget_name = "Webalive Media Widget";

        $this->widget_options = array(
            'classname' => $this->widget_ID,
            'description' => $this->widget_name,
            'customize_selective_refresh' => true
        );

        $this->control_options = array(
            'width' => 400,
            'height' => 300
        );

        parent::__construct($this->widget_ID, $this->widget_name, $this->widget_options, $this->control_options);
    }

    //Backend display of widget
    public function form($instance)
    {
        $title = !empty($instance['title']) ? $instance['title'] : esc_html__("Custom Text", 'webalive_plugin');
        $titleID = esc_attr($this->get_field_id('title'))
        ?>
        <p>
            <label for="<?php echo $titleID ?>">Title</label>
            <input type="text" class="widefat" id="<?php echo $titleID ?>" name="<?php echo esc_attr($this->get_field_name('title')) ?>" value="<?php echo esc_attr($title); ?>">
        </p>
        <?php
    }

    // Front end display of Widget
    public function widget($args, $instance)
    {
        echo $args['before_widget'];

        if(!empty($instance['title'])) {
            echo $args['before_title'] . apply_filters( 'widget_title', $instance['title']) . $args['after_title'];
        }

        echo $args['after_widget'];
    }

    public function update($new_instance, $old_instance)
    {
        $instance = $old_instance;

        $instance['title'] = sanitize_text_field($new_instance['title']);

        return $instance;

        //return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }
}


add_action('widgets_init', function () {
    register_widget("MediaWidget");
});